### ISSUE TITLE
Unexpected output in `inferier-python-mode` buffer

### ISSUE THREAD

**Issue by liebkne** [minad/corfu#102]
With the test script below, typing/completing in an `inferior-python-mode` buffer sometimes gets unexpected outputs like 

<img width="1072" alt="Screen Shot 2022-01-06 at 3 48 11 PM" src="https://user-images.githubusercontent.com/5475262/148347846-bffa88c5-2f1f-4886-a4f2-dc4291565dbe.png">

```el
(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

(require 'package)
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-user-dir (expand-file-name "elpa/" user-emacs-directory))
(package-initialize)

;; Install use-package that we require for managing all other dependencies
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(package-install 'corfu)

(setq corfu-auto t)
(corfu-global-mode)

(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt --pprint"
      python-shell-setup-codes '("import sys; sys.argv = sys.argv[:1]")
      python-shell-completion-native-enable nil)
```

Emacs version: `GNU Emacs 27.2 (build 1, x86_64-apple-darwin21.1.0, Carbon Version 165 AppKit 2113) of 2021-11-18`

**Comment by minad** [comment]
I don't know what is going on here. I tried to debug this quickly but the python completion code is opaque and buggy. For example I got `(wrong-type-argument integer-or-marker-p nil)` errors. The issue is in particular triggered by the setting `python-shell-completion-native-enable=nil`. But it is already not a good sign that the python mode offers different completion modes, which as a result get less coverage. This means that we have two code paths, where the first one does not work under all circumstances and we also have a less tested and less robust fallback code path which is buggy. 

I also tried the noninterruptible capf to check if this is the issue with an aggressive `corfu-auto-delay=0` setting, but it does not fix the issue.

~~~ elisp
(setq corfu-auto-delay 0)
(defun noninterruptible-adv (orig) (funcall (cape-noninterruptible-capf orig)))
(advice-add #'python-completion-at-point :around #'noninterruptible-adv)
(advice-add #'python-shell-completion-at-point :around #'noninterruptible-adv)
~~~

The issue is less pronounced on Emacs 28, there is occurs much less often but I still see it occasionally. Which python shell configuration do you use @jdtsmith?

**Comment by jdtsmith** [comment]
I've experienced this.  I bet it happens while you are typing and completion occurs.  It results from inferior python's non-interruptible completion backend, which corfu interrupts when it notices additional input.  So this behavior is sporadic.  Some output, like gathering the full list of importable modules, takes longer tie, and so is more likely to get interrupted by corfu.  As a result of an interruption, pending process output which was supposed to be hidden (via `python-send-string-no-output`) "jumps the track" and gets put into the buffer.  It is definitely worse with shorter a `corfu-auto-delay`.  Did you ever experience this with company (if you tried that)?  I'm not sure how it handles additional input (while-no-input?).  Note that "native" (readline-based) completion is disabled with  ipython, which results in slower completion, and therefore is more prone to interruption. 

In fact this issue is one of the reasons why I am developing some significant ipython-specific extensions for the inferior python shell I call `ipython-better` (as yet unreleased), which bypasses python.el completion entirely, and uses the in-built Jedi-based iPython completion machinery, among other features.  It works great with corfu.

**Comment by minad** [comment]
> I bet it happens while you are typing and completion occurs. It results from inferior python's non-interruptible completion backend, which corfu interrupts when it notices additional input. So this behavior is sporadic. Some output, like gathering the full list of importable modules, takes longer, and so is more likely to get interrupted by corfu. 

No, this does not seem to be the case. I also reproduce this with the noninterruptible wrapper as I wrote above. But I would have to check more closely. However my motivation to dig into this broken python completion function approaches zero.

> Did you ever experience this with company (if you tried that)?

I did not try.

> In fact this issue is one of the reasons why I am developing some significant ipython-specific extensions for the inferior python shell I call ipython-better (as yet unreleased), which bypasses python.el completion entirely, and uses the in-built Jedi-based iPython completion machinery, among other features. It works great with corfu.

Sounds good! The python.el code is abysmal.

**Comment by doolio** [comment]
FWIW, I've worked around this issue by using the following hook based on your suggestion for `eshell` in the README.

```emacs-lisp
  (add-hook 'inferior-python-mode-hook
            (lambda ()
              (setq-local corfu-auto nil)
              (corfu-mode)))
```
