### ISSUE TITLE
Configurable auto insert for single match

### ISSUE THREAD

**Issue by minad** [minad/corfu#109]
Proposed in #108 by @billop. We could introduce a general `post-command-hook`commit predicate similar to the `corfu-commit-predicate` which is checked in the `pre-command-hook`. A predicate seems like a good solution since the user may want to configure the post-command commit:

* Disable by setting to nil
* Use a predicate which checks for a single candidate
* Use a predicate which checks for an exactly matching candidate, even if there are multiple candidates.
* Use a predicate which checks for an exactly matching single candidate (the current behavior)

**Comment by minad** [comment]
cc @jdtsmith wasn't there some proposal to also generalize the `pre-command-hook` predicate to a function which returns either `quit` or `commit`? Maybe we can find a unified, general solution here.

**Comment by jdtsmith** [comment]
I think the context was misbehavior with edebug.  So I suspect a `quit` Return for such a predicate would fix that.   I actually prefer a single narrowed candidate to auto-commit (which maybe isn’t surprising given that I wrote that snippet).  But company in other contexts does something better and different: places in and highlights the rest of the single completion in-buffer for you to evaluate.  And I like that even better. Not sure why that doesn’t happen in this case.

**Comment by jdtsmith** [comment]
Just following up on this — it seems "disable" could be very useful for supporting in-buffer SPACE-separated orderless filtering with corfu.  This would allow you to fine-tune when to fully _abort_ an auto-completion.  The reality is that many auto-completions are undesired — they are attempting to complete a word which you intend to write out in full (perhaps a brand new variable name, etc.).

At present you may commit candidates (including the implicitly selected 1st candidate) via a predicate, but for _aborting_ auto-completion, you have the choice of doing so on word boundaries, or not.  But it might also be useful to be able to configure this behavior, e.g. to allow SPACE but abort on other non-word characters.  A [reddit post](https://www.reddit.com/r/emacs/comments/sh3lio/orderless_corfu_make_the_component_separator/) points out how challenging it is to use orderless + corfu + SPACE separation, and I do agree that there are many "false positives" to contend with, especially with dabbrev mixed in via cape.  Allowing a bit more tuning for when corfu should "forget about it and get out the way" might really help with this issue.

**Comment by minad** [comment]
I don't know. This all seems to get quite complicated. I think using `corfu-auto=t` with `corfu-quit-at-boundary=nil` is not a good configuration. If you want to use auto completion, just use `corfu-quit-at-boundary=t` and you will be alright. The same applies to `corfu-quit-no-match`. The README should probably more clear about this. There are configurations which work well and some which may get into your way. Your solution, @jdtsmith, to write fine tuned predicates is not something which will get adopted by many people.

**Comment by minad** [comment]
I added some prototype in https://github.com/minad/corfu/tree/pre-post-hooks, where the user can configure pre and post input hooks. This is very general but probably a bit hard to configure.

**Comment by jdtsmith** [comment]
> If you want to use auto completion, just use corfu-quit-at-boundary=t and you will be alright. 

Not if you want to use orderless with default separator in the buffer.  But yes I agree a good default is preferable to the fine-tuning approach.  Since "use orderless in the buffer!" is one of the primary draws & points of distinction for corfu, it's probably worth a more detailed setup guide in the wiki (apart from usage for lsp modes).  For example README says:

> Cofu supports completion styles, including the advanced [Orderless](https://github.com/oantolin/orderless) completion style, where the filtering expressions are separated by spaces

(aside: note 1st word typo).  This may be taken to imply that spaces with orderless are a sensible solution.  And most people will turn on corfu-auto.   

One idea I had was to make a "special space" bound to `S-SPC`, which just inserts space, but which can be added to `corfu-continue-commands`.  But alas continue does not outrank quit-at-boundary.

**Comment by minad** [comment]
> Since "use orderless in the buffer!" is one of the primary draws & points of distinction for corfu, it's probably worth a more detailed setup guide in the wiki (apart from usage for lsp modes). For example README says:

Sure, more documentation is better. But to be honest, there are many reasons why the documentation is lacking:

1. There are not many contributions, so I prioritize what I need and use. The consumer/contributor ratio to my packages is maybe 1000/1. This is of course a common problem of most open source projects. I think it would be kind of nice if people who experiment with new packages and give them a run give some feedback, create issues, add to the wiki, or even better directly create improvement PRs. I am not saying that much time should be spent beyond the time already needed for the configuration itself, just documenting steps and noticing missing details. Unfortunately this is not that a common pattern which is unfortunate. If you look around there are many literate configs where some special settings and tweaks are documented. But it rarely leads to contributions. I think the Emacs community could do better here, in particular since Elisp and Emacs is so much about remixing and tweaking. I recently tried to be a bit better there myself, and started creating more smaller improvement PRs to packages which I use.
2. My direct benefit from writing documentation is almost zero. The only benefit is if things are documented to look them up later again. Of course there is an indirect benefit if users contribute back after having tried the package, which only happens if the existing documentation is already good.
3. I don't consider myself a great writer and I am not a native English speaker. Therefore my documentations and READMEs mostly grow from something basic and I add pieces here and there. But I don't start with the plan to write a great coherent manual. There is also the aspect that Emacs documentation is scattered across docstrings and separate manuals. I haven't found the best style here yet. Ideally everything would be documented in the el file itself in the commentary section, such that the el file is self contained. However there is no way around having an accessible README manual which is directly rendered on github, elpa etc.
4. There is not a single way to use Corfu. There are many configuration possibilities and alternative modes of operations. Therefore Corfu relies on users contributing their experiences and documenting their configurations. The same applies to Capf/backend issues. Having them documented relies so much on user experiences since I cannot try all the different setups myself one by one.

> This may be taken to imply that spaces with orderless are a sensible solution. And most people will turn on corfu-auto.

How you derive an implication from that is unclear to me. The configuration example also says "Optionally". The problem is that completion styles are complicated, not well known and badly documented from the side of Emacs. Just take look at [my orderless configuration](https://github.com/minad/consult/wiki#minads-orderless-configuration). In the context of in buffer completion the situation becomes even worse and there are more degrees of freedom regarding the precise behavior of completion.

> One idea I had was to make a "special space" bound to S-SPC, which just inserts space, but which can be added to corfu-continue-commands. But alas continue does not outrank quit-at-boundary.

This won't work. The only thing which works is to use a separate which is a valid identifier character. This workaround is already described in the Orderless README as workaround for Company. I also experimented with such hacks back then with Company, for example inserting "_" but propertizing the character with a display property showing a space instead.

**Comment by jdtsmith** [comment]
> I think it would be kind of nice if people who experiment with new packages and give them a run give some feedback, create issues, add to the wiki, or even better directly create improvement PRs.

I do too... which is why I've contribute all of the above!  This was not a call for you to write documentation, but instead to discuss a good sensible config for people who want to use orderless in buffer with corfu-auto.  But maybe there isn't a general one.

**Comment by minad** [comment]
> I do too... which is why I've contribute all of the above! This was not a call for you to write documentation, but instead to discuss a good sensible config for people who want to use orderless in buffer with corfu-auto. But maybe there isn't a general one.

Yes, you do and I appreciate that! I believe there is no general perfect solution, so Corfu just tries to allow multiple modes of operation by being flexible. Corfu started more opinionated (it didn't even have auto completion), but got more flexible over time. In contrast Vertico is much more opinionated or has a more fixed interaction model. But minibuffer completion is just so much more restricted and simpler. It does not interfere with your editing automatically, there is no context and so on.

**Comment by jdtsmith** [comment]
I'm experimenting with using a word syntax unicode character as the orderless separator (`⚋` = `"\u268b"` at present), which I can enter with `S-SPC` to separate filter components.  The only thing I wish is for a simpler faster way to "abort the entire operation", so I don't leave any random characters in the file if I change my mind entirely. I need to `ESC ESC ESC` twice(!) to undo buffer changes.  For this I am trying:

```elisp
 :bind (:map corfu-map
	      ("C-S-g" . (lambda () (interactive)
			   (corfu--goto -1)
			   (corfu-reset)
			   (corfu-quit))))
```

**Comment by jdtsmith** [comment]
OK, I have a corfu-auto + orderless setup that works very well for me.  Happy to put it on the wiki if it isn't too esoteric.  The idea is:

- Enable quit-on-boundary.
- Use a special unicode word-syntax character (in addition to space) for the orderless component separator.  "[ \u268b]" is my current choice (that char looks like `⚋`).  
- Bind `M-SPC` in corfu-map to insert this special character.
- Advise `corfu--post-command` to turn _off_ (via let-bind) `corfu-quit-at-boundary` _if the input contains this special separator character_. 

This works really well in practice.  All I have to do is remember to `M-SPC` instead of `SPC` with corfu _the first time only_ when I want to use multiple orderless filters.  And the default quit-on-boundary basically eliminates _all_ the false-positives, e.g. defining new variables, random words in strings or comments that my cape-ified dabbrev-enabled capf throws, etc.  But still lets you use full orderless power with regexps, etc. in buffer.  The only small drawback is the potential for unicode chars to persist in your buffer (if you `C-g` with a multi-component filter), hence my interest in a quick undo-and-quit, above. 

Thoughts?  Suggesting an advice is obviously not ideal for the wiki. Is there a predicate config option you are considering which might work instead for this `corfu--post-command` `:around` advice?

```elisp
  (defun my/corfu-disable-quit-with-orderless-advice (func)
    (let ((corfu-quit-at-boundary
	   (not (seq-contains (car corfu--input)
			      my/orderless-unicode-separator))))
      (funcall func)))
```

**Comment by minad** [comment]
This sounds like an interesting approach. Maybe it even makes sense to adopt this quit at boundary on/off switching by default for a user configurable separator. This goes hand in hand with your #118 where we essentially also introduce a user configurable separator character. We could introduce a variable corfu-separator-char and magically use it for both #118 and quit at boundary toggling. Then I would remove corfu-quit-at-boundary as public variable, essentially replacing it by corfu-separator-char.

**Comment by jdtsmith** [comment]
Thanks.  Right now quit-at-boundary is always off by default.  Such a change would make it "usually on, but off with a special char".  This might surprise people who don't use corfu-auto.  They may be used to not having to worry about syntax, just having the full power of orderless in-buffer.   So perhaps we could overload the meaning of quit-at-boundary to allow it to be some symbol (`'separator` ?), which means use a new (and default `nil` corfu-separator-char) to toggle the quit-at-boundary behavior?  But yes, reusing this to help with the prefix-filtering also sounds good.  And of course that is more flexible for some future orderless successor.

**Comment by minad** [comment]
There is no need to worry about such a confusion. The first word/prefix is already not free to use arbitrary syntax for many capfs. Based on the prefix the capf decides to trigger completion or not.

We have to think about this more but maybe it is okay to really introduce this as replacement for quit-at-boundary instead of the overloading. It seems like a clear improvement over the status quo. When setting the separator to space we regain the current behavior.

**Comment by jdtsmith** [comment]
Good point.  Sounds worth a try.  People who change the quit-at-boundary default are probably all trying for a comfortable orderless setup anyway (and its doc even mentions "If automatic quitting is disabled, Orderless filter strings with spaces are allowed").

**Comment by minad** [comment]
I created a separate issue for the quit-at-boundary discussion.

**Comment by minad** [comment]
I fixed this issue by introducing a variable `corfu-insert-single` in https://github.com/minad/corfu/commit/5b0fdd9ec99f8490902a3c2edf46958301fb6db1, which can be set to nil to disable this behavior.

I thought a while about this and decided to go with the simpler approach instead of introducing additional predicate functions. For this reason I also removed the `corfu-commit-predicate` and replaced it by the value `insert` for the variable `corfu-preview-current`. I want to take a step back here on complexity and focus on features which are easily configurable and matter to most new users.

This means that @jdtsmith's auto-commit snippet from the [wiki](https://github.com/minad/corfu/wiki#auto-commit) stops working. However it seems to me that we essentially win nothing by the predicate. Instead one can as well advise the `corfu--pre-command-hook` or introduce a custom `pre-command-hook`, which is only active when the Corfu popup is open and which contains the logic from @jdtsmith's `my/corfu-commit-predicate` and then calls `corfu-insert`. @jdtsmith Please let me know what you think about this change and if you manage to get your fancy commit snippet to work despite the removal of `corfu-commit-predicate`. I should note that I don't consider the `my/corfu-commit-predicate` configuration anymore - this is programming your own logic. It is good that this is possible of course, this is Emacs after all, but we should not let us guide design questions only by ease of extensibility/hackability, but rather if we can cover the most important use cases with simple means. Otherwise we would have to clutter the package with way too many hooks. Fortunately there is already the advice mechanism!

If it turns out that it is hard to achieve certain configurations only by introducing hooks/predicates which are called before and after input, we could still go that route. But for now I prefer the simpler approach.

**Comment by jdtsmith** [comment]
Here are some thoughts.  I fully understand and support the desire to simplify and improve the default behavior.  Indeed, a fair bit of my commit predicate was aiming at the problem of "lingering `No Match`" at times when I wasn't actually interested in completion.  These as mentioned are basically eliminated by the new special boundary separator handling. But there are other impacts.  

But first a couple positives: it looks like you added a "go back to buffer prompt" on special separator insertion, which is smart and works well, since usually, if you've started selecting with arrow keys, but decide you want to narrow further, you often do so by adding another filter term.  Also, the mechanics of "preview and auto-commit" going together are quite intuitive and non-surprising for users.

The one behavior of my predicate I know I will miss: I add orderless filter terms to whittle it down to one candidate, then go about my typing and it gets auto-inserted (what else could I mean?).  I used that _a lot_.  E.g.:

```elisp
(corfu--[M-SPC]xa)
```

used to insert `(corfu--affixate)` and off I'd go, but now I get the dreaded "No match", have to delete the `)` and hit return.

On this same topic, in terms of new users especially, I worry about how these changes interact with the default "first candidate pre-selected" feature that was added a while ago.  Since you can never select it and therefore it can never be previewed, _even if it is the only candidate_, this basically mean there is _no way to auto-commit_ the 1st candidate, _ever_.  This is doubly unfortunate since the first candidate is _more likely than average to be the one you actually want_.  

This broken symmetry in committing-by-continuing-onward is a bit jarring.  You basically have to remember "if I want the first (or only) candidate, I have to hit return or (maybe) tab; for other candidates I can select them first, see them previewed, and then continue typing".  Such broken symmetries in my experience add a slight viscosity to the completion process, which users may interpret as slowness or inconsistency.  I can't think of a good solution to this.  One possibility is to stop pre-selecting the first candidate, or "softly" select it, but that road has been traveled.  To help with auto-committing "single remaining candidates", you could of course add a small addition to your `'insert` logic: "also auto-insert if you've whittled the list to just one candidate, and have _added_ to the input".  Based on its doctoring, it would seem `corfu-insert-single` should do this, but it doesn't seem to do anything for me (I think because of `(equal (car corfu--candidates) str)`).

**Comment by jdtsmith** [comment]
Also, I know some people are opposed to "preview" and I don't blame them, given how information-packed the in-buffer text can be.  The new changes mean you can never auto-commit unless you also preview (and again, never for the 1st or only candidate).  Obviously some of this stuff can be re-implemented as advice, but most users shouldn't be playing with that, and of course there's a higher potential for advice to get broken down the road.

**Comment by minad** [comment]
I am not sure I get your point. Even with the current simplification, the existing default behavior is preserved. You can still implement your own custom committing behavior with a custom `pre-command-hook`. The only difference is that Corfu doesn't offer special support for that. But the special committing behavior was already way beyond what most users are willing to write as configuration. Therefore nothing is lost here.

As for the symmetry breaking - you are looking at it the wrong way in my opinion. As soon as you preview candidates by scrolling, the prompt is not visible anymore. At this point it looks as if the candidate has already been entered. Therefore it is natural to take the previewed candidate as existing text and treat the following input as input which comes after the candidate. The symmetry breaking only occurs since we cannot always preview the first candidate right away, but this is a different discussion than the committing discussion. Of course if people dislike the preview, it is easy to disable this.

> So hopefully we could improve auto-committing behavior for the first/only candidate somehow.

Do you have concrete suggestions about this. I don't think that the [solution from the wiki](https://github.com/minad/corfu/wiki#auto-commit) is a good answer.

**Comment by minad** [comment]
I just looked through https://github.com/search?q=corfu-commit-predicate&type=Code and found like 4 uses of `corfu-commit-predicate`, which were essentially copies of your `my/corfu-commit-predicate`. But I didn't find any kind of original or otherwise special code. As I mentioned, you can adapt the snippet from the wiki that it works even without `corfu-commit-predicate` by writing your own hook. It would be good to adapt the example in the wiki accordingly.

**Comment by minad** [comment]
Regarding https://github.com/minad/corfu/issues/109#issuecomment-1037392064, I renamed corfu-insert-single to corfu-on-exact-match, which is more accurate.

> I’m not worried about losing the config, much of which isn’t as useful anymore. I guess the simplest possible distillation is — how do I auto commit the 1st/only candidate? Especially if I’ve done the work to whittle the lost down. But there might not be a general way that satisfies all cases.

You can write an advice to `corfu--pre-command-hook` which calls `corfu-insert` if you want to commit. There you can reuse the code from the wiki. Besides that I don't know if we find a good solution for "general auto commit of the first candidate".

**Comment by minad** [comment]
@jdtsmith Since we talked about the symmetry issue of `corfu-preview-current` again, I wanted to mention the option `corfu-preselect-first`, which if disabled allows you to preview the first candidate. However then we get the magic RET behavior of `corfu-insert` again, where the first candidate is committed despite the first candidate not being selected, which is another symmetry breaking :grimacing: 

We could try to remove the special behavior of `corfu-insert`, but I assume that this would hurt the usability for users of `corfu-preselect-first=nil`. So I agree that we have these small quirks around the handling of selection, but I think Corfu is still doing very well now. I am using it mostly in the default settings (with corfu-auto=t) in Eshell, Org, the minibuffer, Elisp and programming buffers, with the Cape Capf and the [Tempel](https://github.com/minad/tempel) Capf. Overall I am never bitten by odd behavior and it speeds me up. As additional configs I am using the ones described in the README (for minibuffer and eshell, corfu-insert-and-send).

**Comment by jdtsmith** [comment]
I agree the defaults have improved a lot!  I've cut out quite a bit of my special config.  And there really are a lot of good ways to narrow to and insert the candidate, compared to corfu's main completion-in-buffer competition  (which I switch back to compare to, occasionally).  I can:

- enter more filters to get the desired one up top, and hit Ret.
- navigate down to a candidate and then just continue typing whatever character should be next. 
- Hit Tab if there is only one candidate.

Really a first class tool.  M-SPC works really well for orderless, and took little time to adapt to.  As a bonus, if you accidentally use it in vertico, no problem, a space still gets inserted!  And quit-no-match on the first term with `'separator` is also just perfect, the get-out-of-my-way prescience is very good.  One minor feature corfu lacks compared to its competition is mouse-selection and mouse scrolling of candidates.  I wouldn't really use them, but I bet many do. 

>  I wanted to mention the option `corfu-preselect-first`

Indeed I had forgotten about that one, thanks for the reminder.

> the first candidate is committed despite the first candidate not being selected, which is another symmetry breaking

Right. Hard to say which should take priority — preview-ability or implicit selectability.  My "soft selection" idea was targeting this very issue, by making it clear that (for the 1st target anyway), there are two "forms" of selection — implicit and "active".   But that's still a special case, and not necessarily clear what it means at a glance.  The main competitor has no preview or auto-insertion, and also pre-selects the 1st candidate, so that might be more familiar to people coming over. 

I may advise `corfu--pre-command-hook` or see how I fare without it.   Thanks for your work on corfu.  I suspect it will really take off in the next year.

**Comment by minad** [comment]
Thanks for the kind words! Many of the recent improvements were only possible thanks to your persistent, constructive feedback and your good ideas. I added corfu-mouse to the [extension wishlist](https://github.com/minad/corfu/issues/103), but it could be that we will have a hard time to implement mouse selection. Child frames are really brittle with regards to mouse clicks, since they may get the focus and break in other weird ways. For this reason I entirely locked this down and ensured that all mouse events are ignored in the child frame. In combination with Cape, Corfu is really not missing much anymore. As I already mentioned a few times, I consider it most important to make sure that the popular backends work well, which will help people adopt it. I am quite happy how Corfu turned out recently, in particular the corfu-separator change is great and I also managed to fix some child frame flicker/display issues. Corfu really goes out of the way now and feels very unobtrusive, which was always the goal.

**Comment by minad** [comment]
Ah, one thing I've seen mentioned a few times - Corfu lacks terminal support. I am happy to use `consult-completion-in-region` there or `mct-region-mode`, but this is an advantage of Company. Maybe Corfu could get support for multiple display frontends, e.g., an additional one based on [popup.el](https://github.com/auto-complete/popup-el). However I don't consider terminal Emacs a priority. None of my packages focuses on terminal usage. Emacs itself is a terminal and a shell. Recently I even switched to Eshell as my main shell, which works surprisingly well. The killer features are redirection to buffers and full access to Elisp.
