### ISSUE TITLE
Popup stays open when switching windows

### ISSUE THREAD

**Issue by minad** [minad/corfu#112]
Auto completion in scratch -> switch to eshell via C-c e.

**Comment by aconchillo** [comment]
Popup stays open for me despite having, both in lsp-mode or geiser.

```
  (setq corfu-quit-no-match 'separator)
```

**Comment by minad** [comment]
@aconchillo Your bug is probably a different bug. It sounds like an issue in your configuration. Can you reproduce this with a minimal recipe based on emacs -Q, with only a minimal set of packages loaded?

**Comment by aconchillo** [comment]
@minad Yes, my bad. The problem was because I copy pasted this:

```
(use-package orderless
  :init
  ;; Configure a custom style dispatcher (see the Consult wiki)
  ;; (setq orderless-style-dispatchers '(+orderless-dispatch)
  ;;       orderless-component-separator #'orderless-escapable-split-on-space)
  (setq completion-styles '(orderless)
        completion-category-defaults nil
        completion-category-overrides '((file (styles . (partial-completion))))))
```

With this corfu doesn't quit when there's no match but I am sure there is more to tweak. Since I'm not sure I need orderless I just removed it and corfu quits as expected now.

**Comment by aconchillo** [comment]
A little bit more info. If `orderless` is not setup and you type for example `(use-package`, as soon as you press space the popup will go away (which is my preference). With orderless setup (with above config) if you type `(use-package` and then you hit space, the popup doesn't close. You need to keep typing (something else different than spaces) for the popup the close, but then it will open again for the next completion and so on.

**Comment by AkibAzmain** [comment]
Is this issue still present?

**Comment by minad** [comment]
Yes, this happens mainly when invoking a command which switches the buffer after some time (run-ar-time). Then Corfu will not observe the switch and not close the popup. But it is a rare problem.

**Comment by AkibAzmain** [comment]
Then Corfu can add some function to hooks like `window-scroll-functions`, `window-size-change-functions`, `window-state-change-functions`, `window-buffer-change-functions`, `window-selection-change-functions`, and obviously `window-configuration-change-hook`.  Note that all functions in these hooks are not handled in the same way, `(info "(elisp) Window Hooks")` describes them all.

**Comment by AkibAzmain** [comment]
I won't try to implement this right now, because I have completed paperwork yet, and maintaining a fork of a package requires simply too much effort (I'm already doing this for Eglot, see https://github.com/joaotavora/eglot/pull/839).

**Comment by AkibAzmain** [comment]
Yes, I think, there is no legal problem.  But I have some personal problems, preventing me to do it now.

**Comment by agzam** [comment]
Is there at least a function to remove the stale pop-up? It's kinda annoying when it weirdly floats around, e.g. when using tab-bar mode.

**Comment by minad** [comment]
@agazam When does the issue occur in your setup? Can you create a minimal recipe starting from emacs -Q? We can probably handle all these issues as described in https://github.com/minad/corfu/issues/112#issuecomment-1168911448.

**Comment by agzam** [comment]
I mean aside from the issue, I'm sure there's some mechanism to remove the existing pop-up, right?

What does corfu use? is it a posframe? Can I find it in `(frame-list)`, doesn't it have a unique attribute?

**Comment by minad** [comment]
@agzam child frame. See corfu--frame.

**Comment by agzam** [comment]
I'm sorry I'm sorry for not cooperating, I just re-installed my system anew and I'm still trying to restore things, I have not installed chemacs2 yet. Also, I switched to corfu just a few days ago and haven't had a chance to explore the code.

And this issue is a tough one, it's not easily reproducible. It can happen often enough to feel annoying, but now I can eval `(delete-frame corfu--frame)`.

It's not ideal but works most of the time. Sometimes though, it still leaves a blank artifact - a rectangle area that has nothing but still blocks the text behind it. Last time that happened I run something like:

```
(pp (seq-map
  (lambda (x)
    (frame-parameters x))
  (frame-list)))
```

and tried to find that frame, but couldn't figure out which one I needed to delete, and as I tried to type a command, corfu popup appeared while the ghost frame got removed.

**Comment by minad** [comment]
@agzam In my setup, this problem occurs almost never. Corfu is quite solid overall. I would really need a recipe to reproduce the most common scenario, if we want this fixed. It could also be a Mac-specific issue. In that case, I cannot do anything about it without help since I don't have a Mac around. But I recommend switching to a free platform anyway. ;)

**Comment by agzam** [comment]
> this problem occurs almost never. Corfu is quite solid overall.

Yes, this doesn't happen often, that's why it's difficult to reproduce.

> It could also be a Mac-specific issue. 

Could be. Also, I'm using Emacs 29. With --native-comp flag. Any of these factors can contribute to the cause. That's why I'm hesitant on trying to repro it on emacs -q. See, I have never complained about the issue. For me, a function to remove all the corfu frames that I can bind to a key (at least for now) is quite sufficient.

> I recommend switching to a free platform anyway

I know, right? It's not up to me, though. Unfortunately, my employer, for a bunch of bureaucratic reasons, painted as "security", forces me to use a Mac.

Anyway, apologies for the noise. And thank you for all the amazing work you do. I know, could be extremely frustrating, when someone complains about the work that you enthusiastically shared without asking for a single dime or any appreciation for it. But at this point you probably know, a lot of people in the Emacs community seriously love the completion stack you've created, and I am with them. You have my sincerest gratitude.

**Comment by Eason0210** [comment]
Hi @minad 

I can reproduce this issue with the steps as below:

1. `emacs -q` to launch Emacs, and then install corfu `(package-install 'corfu)`
2. enable auto complete and set `(setq help-window-select t)`
```
(global-corfu-mode 1)
(setq corfu-auto t)
(setq help-window-select t)
```
3. Type some code in `*scrath*` buffer, until the candidate window pop up, such as type `(mes`
4. <kbd>C-h k </kbd> and then<kbd> C-g </kbd>, now you will see the issue as below picture.

I am using Emacs 29.0.50, macOS 13.0.1

<img width="627" alt="image" src="https://user-images.githubusercontent.com/47546452/202859065-45fcbfe3-bc5f-427e-b023-4946d50bd812.png">

**Comment by minad** [comment]
On 11/19/22 16:54, Eason Huang wrote:
> I can reproduce this issue with the steps as below:
> 
>  1. |emacs -q| to launch Emacs, and then install corfu |(package-install
>     'corfu)|
>  2. enable auto complete and set |(setq help-window-select t)|
> 
> |(global-corfu-mode 1) (setq corfu-auto t) (setq help-window-select t) |
> 
>  3. Type some code in |*scrath*| buffer, until the candidate window pop
>     up, such as type |(mes|
>  4. C-h k and thenC-g , now you will see the issue as below picture.
> 
> I am using Emacs 29.0.50, macOS 13.0.1

I cannot reproduce in on Emacs 28, Linux/X11. This is either a 29
regression or a Mac issue. From my experience on the issue trackers,
Emacs on Mac has many issues.

**Comment by Eason0210** [comment]
> I cannot reproduce in on Emacs 28

I can not repoduce in Emacs 28.2 too, on macOS.
Now it clear, it only happen on macOS with Emacs 29.
