### ISSUE TITLE
Using Corfu with corfu-auto for Address Completion in Message-Mode (and Derived Modes)

### ISSUE THREAD

**Issue by c-alpha** [minad/corfu#128]
I wanted to use `corfu`'s popover-UI with `corfu-auto` for completing email addresses in `message-mode` buffers, and stumbled on similar issues as @utkarsh181 in #121. I hence had a look to how `notmuch-message-mode` integrates with `company-mode` to show the `company` completion UI for completing email addresses.

It seemed to me that this information could perhaps help in achieving what I had in mind, so I thought I'd share it here, and see what you guys think.

Text completion im `message-mode` is different from most (all?) modes in that one will want to use different sources for completion candidates in different parts of the buffer. In the header area, you will want email addresses (To, From, Cc, Bcc, Reply-to), newsgroups (groups), and plain text (Subject), whereas in the body area you will likely want plain text (e.g. `yasnippet`) only.

To accommodate for this, `message-mode` provides some infrastructure. 

While in `message-mode`, the list `completion-at-point-functions` by default contains a single entry only, which is `message-completion-function`. That function detects whether point is in the header, or the body area. In the latter case (body) it hands completion on to other `completion-at-point-functions` (including those of parent modes). Hence, `corfu-auto` mode works just perfectly in the body of `message-mode` buffers. In the former case (point is in the header area), the alist `message-completion-alist` is consulted. It contains pairs of the form `(regex . fun)`. For the first match of a header line against `regex`, the associated `fun` is called for completion. That `fun` must comply with the same interface as any function for `completion-at-point-functions`.

Enter `notmuch-message-mode`, which is derived from `message-mode`. When it comes to text completion, the only add-on over `message-mode` is that it adds an entry to the beginning of `message-completion-alist`, which registers the function `notmuch-address-expand-name` for all header lines which hold email addresses.

`notmuch-address-expand-name` has the following structure:
```elisp
(defun notmuch-address-expand-name ()
  (cond
   ((and (eq notmuch-address-command 'internal)
	 notmuch-address-use-company
	 (bound-and-true-p company-mode))
    (company-manual-begin))
   (notmuch-address-command
    ;; minibuffer completion code stripped for clarity
    )
   (t nil)))
```

The interesting bit seems to be the first case of the `cond`, when the company popover-UI is brought up (because that's what I wanted to achieve with `corfu`). The notmuch developers are calling `company-manual-begin` in that case.

I toyed around with my own function being registered in `message-completion-alist` instead of `notmuch-address-expand-name`:
```elisp
(defun corfu-address-expand-name ()
  (let ((completion-at-point-functions (list #'notmuch-address-expand-name))
        (notmuch-address-use-company nil))
    (corfu-manual-begin)))
```

Apparently `corfu-manual-begin` doesn't exist (yet?), and in its place I have tried `(completion-at-point)`, `(corfu--auto-complete (corfu--auto-tick))`, `(corfu-complete)`, and perhaps others I don't remember now. They all produce either `nil`, or various error messages. So it seems we're in a rather specific context at that point.

Thus, my conclusion would be that, in order to be able to use `corfu` with `corfu-auto` for completing email addresses im `message-mode` buffers, a `corfu-manual-begin` function of sorts would be needed. Any thoughts on adding that?

_**Note:** Due to my admittedly quite limited understanding of how text completion in `message-mode` works in detail, there may well be much better, and more elegant ways of achieving this. Any hints appreciated._

**Comment by minad** [comment]
I am sorry, but I have a hard time to understand what this issue is about. There are two APIs offered by Emacs:

- `completion-in-region`: This function is what you want to use if you trigger completion manually given a list of completion candidates (or more generally a completion table).
- `completion-at-point` configured via `completion-at-point-functions`: These functions are used for auto completion and also tried in order if you invoke `completion-at-point`.

Two simple examples:

~~~ elisp
(defun example-cir ()
  (interactive)
  (completion-in-region (point) (point) '("cirfirst" "cirsecond" "cirthird" "cirfourth")))
(global-set-key (kbd "C-c e") #'example-cir)

(defun example-capf ()
  (let ((bounds (or (bounds-of-thing-at-point 'word) (cons (point) (point)))))
    (list (car bounds) (cdr bounds)
          '("capffirst" "capfsecond" "capfthird" "capffourth"))))
(setq completion-at-point-functions '(example-capf))
(global-set-key (kbd "C-c p") #'completion-at-point)
~~~

You can try to complete with `C-c e` or `C-c p`. Notmuch or message-mode should use these Emacs APIs and everything will work well with Corfu. Note that Capfs also work with Company, but `completion-in-region` does not work with Company. Therefore Company comes with its own convention for manual completion, where one calls `company-manual-begin`. Does this help you? I recommend you contact the notmuch developers to help with this issue, since this is not an issue of Corfu. If packages make correct use of the aforementioned APIs eveything should work well with Corfu and as one can see from the examples above, writing such completion functions is a relatively easy task. So in case a package misses a completion function you could also write it yourself, e.g., write a simple mail completion function by obtainaing the mail addresses and then using one of the snippets from above (depending on if you either want manual or auto completion). Besides that I think ebdb provides a completion function for mail addresses.

**Comment by minad** [comment]
I close this since it is not a Corfu issue. Please let me know if you need further information regarding the API usage. Maybe @utkarsh181 can also be of help since I think he produced a patch for notmuch?

**Comment by c-alpha** [comment]
> [...]
> You can try to complete with `C-c r` or `C-c p`. Notmuch or message-mode should use these Emacs APIs and everything should just work. Note that Capfs also work with Company, but `completion-in-region` is not supported by Company. Therefore Company comes with its own convention for manual completion, where one calls `company-manual-begin`. Does this help you?

Yes, it does. Thanks for pointing me in the right direction! I wish there was an easier digestible documentation of what the architecture of completion in Emacs is.

> I recommend you contact the notmuch developers to help with this issue, since this is not an issue of Corfu.

I have seen the patch @utkarsh181 has proposed on the notmuch developers list, and the not so enthusiastic echo it received there. My very personal take would be that a package like notmuch should be agnostic of any completion front-end package and should feed into `compeltion-at-point-functions` only. But then that's perhaps only me...

> If packages make correct use of the aforementioned APIs,

I wish they did, and I wish more packages did!

> completion should work well with Corfu. As one can see from the examples above, writing such completion functions is a relatively easy task. So in case a package misses a completion function you could also write it yourself, e.g., write a simple mail completion function by obtaining the mail addresses and then using one of the snippets from above (depending on if you either want manual or auto completion). Besides that, I think ebdb provides a completion function for mail addresses.

Totally agree.
