### ISSUE TITLE
Need another setting for similar behavior as corfu-quit-at-boundary=nil

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#138]
As discussed [elsewhere](https://www.reddit.com/r/emacs/comments/t38kkh/comment/hytocdm/?utm_source=share&utm_medium=web2x&context=3), people who use corfu-auto=nil are missing the full flexibility of using orderless on any string that corfu-quit-at-boundary=nil provided, even the first component.  The recommendation in the README only solves the issue for SPACE, not for other orderless characters like `!`, `,`, etc.  One idea would be to disable CAPF checking if corfu-auto=nil and corfu-separator=nil.  Or to simply make the CAPF-disabling check "string has a separator char, or corfu-auto=nil".

**Comment by minad** [comment]
The old `corfu-quit-at-boundary=nil` was a setting which went too far, since it disabled the Capf check entirely. It is also inconsistent, see below. After we introduced `corfu-separator` everything got simpler and more consistent. It is better to avoid complications, e.g., adding some heuristics to emulate this behavior. Nevertheless it is still quite easy to restore `corfu-quit-at-boundary=nil` fully in case the behavior is really desired. Disabling the predicate check can be done manually with the following two lines of code:

~~~ elisp
(add-hook 'completion-in-region-mode-hook
  (lambda () (setq completion-in-region-mode--predicate #'always)))
~~~

Then I assume one would also unbind SPC/corfu-insert-separator.

~~~ elisp
(define-key corfu-map " " nil)
~~~

We should probably document this in the README. However I argue that the setting is not such a good idea for consistency reasons. Using the prefix as Orderless component with the full Orderless syntax has never been fully supported. The first Orderless component is better treated as an identifier or literal string. The issue is that at the point where the Capf initializes, the Capf checks the buffer contents and depending on that content it will decide if completion is possible. This means that for manual completion, TAB and subsequent input do not commute. Try these examples:

- `foo, TAB`: This works if comma is recognized as an identifier character.
- `foo TAB ,`: This works with `corfu-quit-at-boundary=nil` but is inconsistent with `foo, TAB`. Ideally comma and TAB should commute.
- `foo[0-9] TAB`: This will never work.
- `foo TAB [0-9]`: This works with `corfu-quit-at-boundary=nil`.

Furthermore we also treat the first component specially regarding the sorting, moving candidates with the prefix to the top of the list. I think this is a nice usability improvement, which makes sense if one assumes that the first Orderless component is a literal string.

**Comment by minad** [comment]
Okay, so I thought about this a bit longer. It seems it is better to bring `corfu-quit-at-boundary` back. This decouples the predicate checking behavior from the value of `corfu-separator`. Like `corfu-quit-no-match` the variable `corfu-quit-at-boundary` accepts the values `nil`, `t` and `'separator`.

**Comment by minad** [comment]
@jdtsmith If you have time, I would appreciate if you go over the relevant README sections again to check if the current documentation is reasonable and comprehensible. I feel Corfu is  difficult to configure thanks to its many settings. This is not really the fault of Corfu but rather of the problem that there does not exist the one perfect way to do completion in buffers. People have different preferences and Corfu is tunable for different usage patterns.

**Comment by jdtsmith** [comment]
Just catching up here.  You make some very good points.  Some people are apparently already used to non-commutativity of Tab and (e.g.) comma.  I agree that the first component is "special"; in fact for backends like LSP, it's even more special. Some CAPFs (or cape'ified CAPFs) examine the string and update their candidates, others don't. Given this it makes more sense to keep the 1st component "clean". So I'd support either approach.  I don't necessarily think you have to bring back the heavy hammer of quit-at-boundary=nil.  In fact your simple "defeat the CAPF check" idea seems workable.  I personally like the "separator indicates non-CAPF quitting" setup quite a bit, but it's also of course possible to disable quitting with a key-based toggle.   Feels like unnecessary complexity though.

**Comment by minad** [comment]
> In fact your simple "defeat the CAPF check" idea seems workable. 

Sure, `corfu-quit-at-boundary` is nothing else than that. Just slightly more accessible than the hook. I don't mind to have this option, in particular if users already relied on it. Furthermore it makes the customization options slightly more orthogonal. As you probably observed I removed the support for `corfu-separator=nil` since this is now handled by `corfu-quit-at-boundary=t`. Above you proposed to introduce special casing in case of the auto mode is used and things like that, but this sounds much more complicated to me than having a set of orthogonal configuration options which can be tweaked individually.

**Comment by minad** [comment]
> I personally like the "separator indicates non-CAPF quitting" setup quite a bit, but it's also of course possible to disable quitting with a key-based toggle. Feels like unnecessary complexity though.

I agree with that. There is no plan to add a key based toggle or to add more complexity. Users could of course write a simple command which temporarily sets `corfu-quit-at-boundary` to nil. But we won't provide that by Corfu ootb.

**Comment by minad** [comment]
I read through the discussion on reddit. @karthink also mentioned that it would be nice to have a persistent help buffer which live updates when you scroll through the candidates. This is a nice idea and I think would be an improvement over the status quo. However I don't want to blow up the core implementation of Corfu too much so I am considering to move out `corfu-show-location`  and `corfu-show-documentation` to a corfu-help.el extension. We will probably see other extensions in the future. I will add this to the #103.

**Comment by minad** [comment]
@karthink can you please open an issue on the corfu-doc repository? I saw that you don't use this package, but I would still find it nice if the package author is notified, if there exist complaints about the package quality or the design. I think your criticism is justified and well-founded, but these issues are fixable if someone tells the author about it. Creating an issue on gh shouldn't take much more time than writing on reddit? Maybe you already planned on doing that?

Personally I am not sure about the best approach regarding package quality. Many packages don't meet my personal quality threshold. Usually I don't use them and I also don't criticize them publicly. If I think a package is fixable or the foundation is okay, then I try to create issues about the observed problems, even if stop using the package after that. Even in cases where the package or the idea are not really that good, it may be worth helping the author with constructive criticism, which helps the developer and the community in the long term. There are many people publishing packages on MELPA, who are beginners or who just started with writing Emacs packages. The hackability is also what Emacs is about, so it is good to support that.

I hope you don't mind my thoughts about this!
