### ISSUE TITLE
TAB-and-Go completion can't expand snippet when working with eglot

### ISSUE THREAD

**Issue by 50ways2sayhard** [minad/corfu#145]
When I work with corfu + lsp, company+lsp/eglot, snippet expansion works well:
1. type "init", and get some candidates, like the first screenshot.
2. press "TAB" and select the first candidate "initState() {...}"
3. continue typing some characters else, and corfu will complete things like the second screenshot.
<img width="587" src="https://user-images.githubusercontent.com/16864600/159716021-ff75fd0f-0b16-41ed-9840-2eb909abf3cf.png">
<img width="388" src="https://user-images.githubusercontent.com/16864600/159717485-db099406-b7c3-4a11-baab-00392e9f0dfb.png">

But working with corfu + eglot, snippet expansion can't work properly. When I follow step above, corfu completes "initState() {...}" as shown in the screenshot:
<img width="546" src="https://user-images.githubusercontent.com/16864600/159718639-04305d32-844c-48a3-92f1-3e9194f80257.png">

Here is my configuration, and the language server is [dart analysis server](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md)
```elisp
(use-package corfu
  ;; Optional customizations
  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-auto t)                 ;; Enable auto completion
  (corfu-auto-prefix 1)
  (corfu-echo-documentation 0.5)
  (corfu-preselect-first nil)    ;; Disable candidate preselection

  :bind
  (:map corfu-map
        ("TAB" . corfu-next)
        ([tab] . corfu-next)
        ("S-SPC" . corfu-insert-separator)
        ("S-TAB" . corfu-previous)
        ("S-<return>" . corfu-insert)
        ([return] . nil)
        ("RET" . nil)
        ([backtab] . corfu-previous))
  :init
  (corfu-global-mode)
  :config
  (add-to-list 'corfu-auto-commands 'awesome-pair-open-round)
  (add-to-list 'corfu-auto-commands 'awesome-pair-open-bracket)
  (add-to-list 'corfu-auto-commands 'awesome-pair-open-curly)

  (advice-add #'keyboard-quit :before #'corfu-quit)
  (add-to-list 'corfu-auto-commands 'end-of-visual-line)

  ;; https://github.com/minad/corfu/issues/12#issuecomment-869037519
  (advice-add 'corfu--setup :after 'evil-normalize-keymaps)
  (advice-add 'corfu--teardown :after 'evil-normalize-keymaps)
  (evil-make-overriding-map corfu-map)

  (defun corfu-enable-always-in-minibuffer ()
    "Enable Corfu in the minibuffer if Vertico/Mct are not active."
    (unless (or (bound-and-true-p mct--active)
                (bound-and-true-p vertico--input))
      ;; (setq-local corfu-auto nil) Enable/disable auto completion
      (corfu-mode 1)))
  (add-hook 'minibuffer-setup-hook #'corfu-enable-always-in-minibuffer 1)
  )

(use-package eglot
  :when (eq my-lsp 'eglot)
  :commands (+eglot-organize-imports)
  :hook (
         (prog-mode . (lambda ()
                        (unless (derived-mode-p 'emacs-lisp-mode 'lsp-mode 'makefile-mode)
                          (eglot-ensure))
                        )))
  :config
  (setq eglot-sync-connect 1
        eglot-connect-timeout 10
        eglot-autoshutdown t
        eglot-send-changes-idle-time 0.5
        eglot-auto-display-help-buffer nil)
  (setq eldoc-echo-area-use-multiline-p nil)
  (setq eglot-server-programs (remove '(dart-mode "dart_language_server") eglot-server-programs))
  (add-to-list 'eglot-server-programs '(dart-mode . ("dart" "language-server")))
  (defun +eglot-organize-imports() (call-interactively 'eglot-code-action-organize-imports))
  )
```

**Comment by minad** [comment]
TAB-and-GO is incompatible with snippet expansion. The assumption is that when you type away with a previewed/selected candidate, the previewed candidate in the buffer stays as is and your next input is appended. See this code:

https://github.com/minad/corfu/blob/c12fe374cf93fe113e55aceea933d9d27949727e/corfu.el#L860-L869

The completion `:exit-function` is responsible for expanding snippets. In this case Corfu passes the status `exact`, which means that **no** expansion should be performed. This means that lsp-mode is actually wrong here - it works as you expected, but it is not the correct behavior. In contrast, eglot does the right thing here. It preserves the candidate as is and does not perform snippet expansion because of `exact`. In order to trigger snippet expansion you have to commit the candidate explicitly with `RET` (`corfu-insert`). The command `corfu-insert` calls the `:exit-function` with the status `finished` which tells the backend (lsp-mode/eglot) to perform expansion. Since you seem to prefer to unbind `RET` you could also dedicate another keybinding for explicit insertion, e.g., `M-RET`.

See also what `company-tng` says about this issue: https://github.com/company-mode/company-mode/blob/299e606435f589aa3024daadb7c249940ed8c36a/company-tng.el#L68-L80
