### ISSUE TITLE
The last completion was cut. in variable-pitch-mode

### ISSUE THREAD

**Issue by zhenhua-wang** [minad/corfu#148]
Thank you for this wonderful package!

I notice that in "variable-pitch-mode", the last completion was cut.

<img width="405" alt="Screen Shot 2022-03-29 at 12 46 42 AM" src="https://user-images.githubusercontent.com/11971417/160549710-d62f9563-78ee-41c3-9bde-a089b84ebbd7.png">

**Comment by minad** [comment]
I opened two issues which keep track of the pixel size issues (#149 and #150). Not sure how difficult it will be to fix those. It seems that most people rely on mono spaced fonts, since these issues haven't been discussed before.

**Comment by jdtsmith** [comment]
Sounds quite plausible, so not really an icon issue I suspect.  Perhaps they wanted to have right alignment working so switched?  They OP could always set `kind-icon-use-icons` to `nil`, followed by `M-x kind-icon-reset-cache` and try again.  This should rule out any issue with the icon (since it will just use text instead).

**Comment by minad** [comment]
> I think we discussed pixel width issues, but not line height. But I could see confusion if the corfu display font has a different height from the buffer font from which the mini-frame height is derived.

Well, I was aware of both issues. I have categorized these scenarios as unsupported in my mind. However it is good to have the issues open to give this some visibility, since it would be nice to ultimately improve this. Maybe someone wants to work on this. 

When we discussed about the pixel alignment (in the context of the icon discussion) I recall that you mentioned pixel alignment as one advantages of the child frame approach of Corfu in contrast to overlay based solutions. Unfortunately we do take advantage of this to the full possible extent.

**Comment by zhenhua-wang** [comment]
Thanks for all the helps. I find out that, this behavior occurs because my theme let `corfu-default` to inherit from `default` face, which is not variable pitch. The annotations are indeed not aligned correctly in variable pitch faces, even in a minimal emacs setting.  I also confirmed that kind-icon works perfect for me.

I have a quick question about annotations: can I force all annotations to appear (e.g. those from elisp mode)? Currently only annotations from `lsp` and `cape` are showing up.
