### ISSUE TITLE
doesn't work in gdb gud

### ISSUE THREAD

**Issue by Dickby** [minad/corfu#157]
I tried it with emacs -Q and only corfu loaded.
the selection with C-n and C-p doesn't work, and if you insert a completion candidate with ret it overwrites the beginning of the line
"(gdb)".

**Comment by minad** [comment]
Thank you for the report! I can confirm this. 

The issue seems to be that the `gud-gdb-completion-at-point-function` has problematic side effects (Ideally completion at point functions are pure). The function seems to temporarily delete the prompt, see the FIXME in https://github.com/emacs-mirror/emacs/blob/f8aa771af3061ceb68aafacd55e8e9e048853f5d/lisp/progmodes/gud.el#L920-L926. The original [bug#18282](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=18282) was closed a few years ago.

Unfortunately these side effects disturb the marker which is used internally by Corfu to keep track of the start position of completion. The issue in Corfu is that I always copy the start marker, which renders the hack in `gud-gdb-completion-at-point-function` ineffective. In contrast, `completion--in-region` copies the start marker only if it is not already a marker:

~~~ elisp
(unless (markerp start) (setq start (copy-marker start)))
~~~

I tried to replace `(copy-marker beg)` with `(if (markerp beg) beg (copy-marker beg))` in Corfu and it seems that the issue is mostly fixed. But there are other issues, e.g., when entering `layout TAB` then I cannot continue to complete the argument. I am not sure if it is easily possible to work around all these issues. It seems better if the gdb-gud capf is fixed properly at the root.

**Comment by chriselrod** [comment]
I'll have to look into this more later, but for now I've disabled corfu mode in gdb.
I've noticed two problems that aren't described here:
Corfu randomly prints a seemingly unfiltered list of possible candidates, e.g.
```
(gdb) p phi.data()[2]
$17 = 0
(gdb) p llvm::llvm_unreachable_internal(char const*, char const*, unsigned int)@plt
p llvm::raw_ostream::SetBufferAndMode(char*, unsigned long, llvm::raw_ostream::BufferKind)
p llvm::raw_ostream::SetBufferAndMode(char*, unsigned long, llvm::raw_ostream::BufferKind)@plt
p llvm::raw_ostream::flush_nonempty()
p llvm::raw_ostream::flush_nonempty()@plt
p llvm::raw_ostream::~raw_ostream()
p llvm::raw_ostream::~raw_ostream()@plt
p localtime_r
p localtime_r@plt
p memmove
p memmove@plt
p memset
p memset@plt
p mkdir
p mkdir@plt
p mkstemp
p mkstemp@plt
p operator delete(void*)
p operator delete(void*)@plt
p operator delete(void*, unsigned long)
p operator delete(void*, unsigned long)@plt
p operator delete[](void*)
p operator delete[](void*)@plt
p pthread_mutex_destroy
p pthread_mutex_destroy@plt
p pthread_mutex_init
p pthread_mutex_init@plt
p pthread_self
p pthread_self@plt
p pthread_setspecific
p pthread_setspecific@plt
p regfree
p regfree@plt
p remove
p remove@plt
p stat
p stat@plt
p std::_Hash_bytes(void const*, unsigned long, unsigned long)
p std::_Hash_bytes(void const*, unsigned long, unsigned long)@plt
```
The list goes on for a while (there is a lot in `std::`...).
2. It also seems to complete very eagerly, adding extra nonsensical/invalid completions on key presses.

I thin these went away when I disabled `(corfu-auto t)`, but `corfu-auto` doesn't do that in other modes.

**Comment by minad** [comment]
@chriselrod I appreciate that you look into this, but to be clear, this is not a Corfu bug. The gdb gud backend is broken and should be fixed in Emacs itself.
