### ISSUE TITLE
Option to right-align annotations

### ISSUE THREAD

**Issue by fbergroth** [minad/corfu#18]
Hi, another happy user here!

Is there any plan for something similiar to `company-tooltip-align-annotations`?

Currently I see:
![image](https://user-images.githubusercontent.com/1211003/116610376-bcc01d80-a935-11eb-9f40-b3dcd44a7bfc.png)

But would prefer to see:
![image](https://user-images.githubusercontent.com/1211003/116610305-aca83e00-a935-11eb-91bc-af8844db5db2.png)

Thanks!

**Comment by minad** [comment]
Please give it a try!

**Comment by fbergroth** [comment]
Looking good!

**Comment by minad** [comment]
See https://github.com/minad/corfu/commit/a56e80e152a555afebe6b8ca1d0963ce4cb93b5f

**Comment by apoorv569** [comment]
How to apply this setting?

**Comment by minad** [comment]
Right aligning is currently not supported.

**Comment by jdtsmith** [comment]
Fairly straightforward to implement by space-padding for fixed space fonts.  It looks possible with mixed pitch.   That would require placing annotation text in the frame’s buffer, measuring pixel sizes, and adjusting specified padding space for alignment.   It can’t be done correctly with overlays so could be a distinctive Corfu advantage.   Thoughts?

**Comment by minad** [comment]
I'd use space :align-to for the alignment and try to avoid performing pixel computations myself in the UI. I've observed before that window-text-pixel-size is slow and unreliable, that's the reason I've avoided it. But please give it a try. If it works fine we can go with that.

**Comment by minad** [comment]
The requirement is reliable and fast. I think for these measurements one has to create a temporary buffer assign it to the frame and measure. I think Emacs 28 also has this documented after I created a bug report.

**Comment by jdtsmith** [comment]
If we try for a `window-text-pixel-size` approach, it’s worth offsetting the frame to line up the prefix to left of candidate text as well, and left-aligning candidates with variable-width prefixes (which could of course include icons).  So basically #38 plus (optional) right alignment of suffix.  

I know you had hoped for some clarity on a new direction in core for affiliation data vs. its presentation.  Not sure if anything has materialized.  If you are still not in favor of “3 item” alignment (even if performant, which I expect it to be from experience), I’ll look at space-padding instead.

**Comment by minad** [comment]
I guess I'd be fine with both. Only criteria - it must be robust and fast. And ideally the code should be maintainable and future proof. Currently the display code is a bit messy due to hacks and fighting with the APIs. If that gets cleaned up or at least doesn't get worse I am fine with it.

**Comment by jdtsmith** [comment]
OK I just read through the long emacs-devel thread from May about the inadequacies of `affixation-function`.  It does seem crazy to give the backend the role of deciding what is a "prefix" and what is a "suffix" vs. some semantic labeling like 'kind 'docsig, etc. which the UI can sort out.  Is it here to stay?  Should we just accept that a list of `(candidate prefix suffix)` is the default standard going forward?

Also, you style the (presumed suffix) results of `annotation-function`, but not `affixation-function`.  Is this intentional?  I'd suspect users configuring the new `corfu-annotations` face would want it to apply to "suffixes" no matter how they arrived.

**Comment by minad** [comment]
> Also, you style the (presumed suffix) results of annotation-function, but not affixation-function. Is this intentional?

Yes, in the context of Marginalia/completing-read this makes sene. affixation is the better replacement going forward where the backend has a bit more control with respect to styling. However it would have been even better to replace this with a decoration function, where the backend can specify fields which are then formatted/aligned by the frontend. This would avoid alignment problems in Marginalia and also styling issues here in Corfu or Company. As far as I know Company didn't implement the affixation-function but instead pushes its own extensions like company-kind, which is semantic. This is not a bad idea, but I would have liked a more general solution (decoration-function) which can have both semantic and non-semantic fields. The non-semantic fields matter most for completing-read where the number of possible annotations is unlimited and we wouldn't want to impose the formatting support of arbitrary data to the frontend. Just look at the number of annotators in Marginalia. Therefore for these annotations the fields should just be strings, which are then aligned by the frontend. Semantic fields make sense for some other data like kind (company-kind rendered differently via font-lock or icons), deprecation status etc.

> Should we just accept that a list of (candidate prefix suffix) is the default standard going forward?

For now yes due to the lack of progress. I had hopes that we could see some progress in Emacs core there. But of course this depends on someone doing the work and submit or apply patches there - feel free to step in. Probably @dgutov is also interested in movement there. However to be honest it seems easier to just invent Company-specific extensions, since this is what Company has been doing for quite some time now.

**Comment by minad** [comment]
This issue has been fixed in https://github.com/minad/corfu/commit/1c7fdb15c200cee9c6836dfc861f7c5216f606e9. However alignment issues still remain, in particular pixelwise computations. See #38.

**Comment by dgutov** [comment]
@jdtsmith 

> OK I just read through the long emacs-devel thread from May about the inadequacies of affixation-function. It does seem crazy to give the backend the role of deciding what is a "prefix" and what is a "suffix" vs. some semantic labeling like 'kind 'docsig, etc. which the UI can sort out.

Indeed.

>  Should we just accept that a list of (candidate prefix suffix) is the default standard going forward?

I hope not. And I fully intend to ignore that piece of the API (it's not really usable for Company, but I assume for Corfu it's the same). I don't have the political standing to get it outright removed in Emacs 28, though, even that it would be the best outcome. And all other participants in said discussion didn't press forward the idea of removal.

@minad 

> Yes, in the context of Marginalia/completing-read this makes sene.

I wonder whether that means that a `completing-read-function` using the Company's popup UI wouldn't many sense.

> However it would have been even better to replace this with a decoration function, where the backend can specify fields which are then formatted/aligned by the frontend.

It's not a bad design, but it doesn't seem an improvement enough over the current state of things (which is calling a number of `:property-x-function`-s from extra-properties in the frontend as needed). So I don't know why we would want to move in that direction, given the backward compatibility costs.

Also note that if the backend specifies named fields (so they can be "formatted by the frontend"), that probably means the fields will be semantic, at least to some degree. Giving a thing a name usually implies that.

**Comment by minad** [comment]
@dgutov 

> I wonder whether that means that a completing-read-function using the Company's popup UI wouldn't many sense.

First I think Company/Corfu are quite distinct from Vertico/Ivy/Selectrum/Helm etc because of the interaction model/completion at point vs minibuffer completion. Otherwise I wouldn't have developed Corfu. The popupdisplay itself is a different question. There are posframe/child frame UIs for at least Ivy and Vertico, so popups obviously work there too. However the Corfu/Company popups are much less obtrusive, so this is where I see a small difference, but this is a subjective. If I look at projects like company-box with rich icons and bells and whistles, this is certainly not the case.

> It's not a bad design, but it doesn't seem an improvement enough over the current state of things (which is calling a number of :property-x-function-s from extra-properties in the frontend as needed). So I don't know why we would want to move in that direction, given the backward compatibility costs.

There are multiple issues which could be solved by a more general decoration function - for once the decoration function could provide a list of semantic fields (company-kind, company-deprecated) etc. Then the function could also provide a list of non-semantic fields which are then aligned by the frontend instead of the backend. If you look at my Marginalia package, there I have big issues to get the alignment right, since I have to compute the alignment basically in the backend. If I could push this to the frontend it would be much better. Of course one could just continue to add more and more `company-x` style functions. I could also invent an extension `marginalia-fields-function` which is then understood by the frontend.

The question is also if you want to rather push in the direction of unification or in the direction of split up completion (minibuffer vs at point). My personal preference is to unify on the API level. This of course does not mean that one should use the same UI for both. The split Vertico vs Corfu/Company can still make sense. From how I understood you, you also like unification (this is how I read your question above). On the other hand all these company extensions push in quite the opposite direction, since most of them only make sense for completion at point and do not work in the context of minibuffer completion tables.

**Comment by dgutov** [comment]
> If I look at projects like company-box with rich icons and bells and whistles, this is certainly not the case.

IDK, the only bell and whistle company-box currently adds is the documentation popup, which is available as a separate setting/mode with Company.

> for once the decoration function could provide a list of semantic fields (company-kind, company-deprecated) etc

As a plist, right? This is available already.

> Then the function could also provide a list of non-semantic fields which are then aligned by the frontend instead of the backend.

But how non-semantic would they be? Would there be more than `left` and `right`? Is there a difference between the contents of `annotation` and the contents of `right`? Is it really feasible to do the alightment if there is no predefined expectations on the contents of `left` and `right`? And if there is going to be more "non-semantic" fields than that, I really don't see how it's going to be possible to go without names. Unless they are simply expected to be treated like cells in a table (to be stretched to the full width).

> I could also invent an extension marginalia-fields-function which is then understood by the frontend.

That still sounds better than `affixation-function` that duplicates `company-kind` at least in one completion function.

> On the other hand all these company extensions push in quite the opposite direction, since most of them only make sense for completion at point and do not work in the context of minibuffer completion tables.

I don't have a strong opinion. All of these properties are going to be optional. I suppose we'll need to see whether there are going to be completion functions that return both kinds, and why.

**Comment by minad** [comment]
> Unless they are simply expected to be treated like cells in a table (to be stretched to the full width).

Yes, this is what it could do and it would be sufficient for packages like marginalia/ivy-rich or completion tables providing multiple metadata fields.

![](https://i.redd.it/6cyuoc0l7j561.png)

> As a plist, right? This is available already.

For all the semantic fields you are right that one could just add functions like `company-deprecated` etc to `completion-extra-properties`.

So maybe the status quo is not that bad and one could just proceed in the same way.

1. Add more semantic functions. I would prefer if the functions wouldn't carry a `company-*` prefix but ideally some agreement could be made on which functions to document in `completion-extra-properties`.
2. Add one `field-function` or `marginalia-field-function` which is not semantic and just asks the ui to properly align the fields.

**Comment by dgutov** [comment]
> I would prefer if the functions wouldn't carry a company-* prefix but ideally some agreement could be made on which functions to document in completion-extra-properties.

Yes, as soon as a function is well-documented and generally agreed on, it can lose the `company-` prefix.

> Add one field-function or marginalia-field-function which is not semantic and just asks the ui to properly align the fields.

`field_s_-function`, right? Returning a list of strings, basically.

**Comment by jdtsmith** [comment]
> However to be honest it seems easier to just invent Company-specific extensions, since this is what Company has been doing for quite some time now.

You could take a note from browsers, where experimental css features are introduced first as e.g. `-webkit-transition`, and eventually superseded by universal keywords (`transition`). So consider the company keywords relics of the "browser-specific" burn-in period, then accept and standardize on a set of uniform property names everyone can agree on.  Since it's "just a convention", there's not a real need to enforce it in core or change anything.  If the major backends target your adopted keywords, that becomes a de facto standard. `'kind` is generically useful, for example, nothing company-specific about it.

**Comment by dgutov** [comment]
@jdtsmith 

> You could take a note from browsers, where experimental css features are introduced first as e.g. -webkit-transition, and eventually superseded by universal keywords (transition).

I think that was always the intention here as well.

@minad 

Speaking of "non-semantic" fields and Marginalia, though. I'm looking at the screenshot above and see different columns printed with different colors. Does it mean that the backend applies the faces to the field values itself? Or will do that, at least, in the new proposed scheme?

**Comment by minad** [comment]
> Speaking of "non-semantic" fields and Marginalia, though. I'm looking at the screenshot above and see different columns printed with different colors. Does it mean that the backend applies the faces to the field values itself? Or will do that, at least, in the new proposed scheme?

Yes it does that currently. My idea would be to allow the backend to specify certain hints on how the values should be formatted, e.g., color and alignment. Furthermore the fields are named so the frontend could add special support based on the semantic field names. But the idea is to allow some kind of graceful upgrade, where the frontend can work well even if not all of the backend metadata is understood. Adding semantic support for each of the possible fields supported by arbitrary backends is simply out of the question. It works in the context of company where the amount of metadata is limited, but in the context of Marginalia/ivy-rich it does not work since there the amount of metadata is much richer.

Btw, I just added support for the semantic company-deprecated function to Corfu (https://github.com/minad/corfu/commit/8dad236d18ac98f1d672a5cafe08486cb239db5e). So far I support company-deprecated, company-docsig, company-location and company-doc-buffer. However the company-location and company-doc-buffer features could be supported in a better and more general way by [Embark](https://github.com/oantolin/embark), since these are essentially actions on the candidates. Support for company-kind is more difficult because of icon support. Furthermore I haven't looked into company-match, but this is an extension I also disagree with since match highlighting is applied by the completion styles in Corfu.

**Comment by minad** [comment]
> But up until now you have managed without that, right? And managed to assign correct faces to fields without being overwhelmed by their number?

This is not a reasonable observation. We wrote the annotator functions which define all the fields and *at the same time* we style them. All in *a single package*. This would be different when the backend defines many semantic fields and the frontend ui has to implement them all. Then one would have a hard time to implement all the fields in all the frontends. Note that Marginalia works as is in Vertico, Selectrum, Ivy, default completion and maybe more UIs - all without any kind of special support in the UIs.

> I suppose. The idea with location is it can be handy to look up the definition during completion.

It is a good idea, therefore I've also implemented it. These are certainly the most common actions. I just mean that Embark is the generalization of that, which would basically free all the backends and frontends of implementing this feature. However this is hypothetical since as of now Embark has no support for Company/Corfu. I see Company/Corfu completion as a more limited form of completion than minibuffer completion. In the minibuffer a much richer interaction is possible thanks to Embark.

> Since Corfu uses overlays, just like Company does, the implementation could be largely copied. It would be handy to have a common library of icons, though.

Corfu uses child frames, not overlays. Yes, I am waiting for an icons library or I thought before about making an svg icons library, probably based on the vscode icons first. It could be auto generated from the vscode icons specification. Maybe this would be a good point for collaboration if we create a common library which could be used by Company and Cofu and maybe also for minibuffer completion.

> company-match is a way to override completion-styles's highlightings. I'm not sure of the exact applications these days, but apparently it's more useful for the users of Emacs 25 and 26: company-mode/company-mode#798 (comment)

Thanks for the clarification!

**Comment by dgutov** [comment]
> This is not a reasonable observation. We wrote the annotator functions which define all the fields and at the same time we style them. All in a single package. This would be different when the backend defines many semantic fields and the frontend ui has to implement them all. Then one would have a hard time to implement all the fields in all the frontends.

It might be that you're looking for some middle layer. E.g., backend would present an arbitrary list of semantic fields, and then some helper/middleware/lib shared by a number of table-supporting frontends would associate faces, alignments, etc, with them.

> Corfu uses child frames, not overlays.

Doesn't matter much, actually. `company-posframe` shows the same icons using the display strings produced by the built-in popup implementation.

> Yes, I am waiting for an icons library or I thought before about making an svg icons library, probably based on the vscode icons first. It could be auto generated from the vscode icons specification. Maybe this would be a good point for collaboration if we create a common library which could be used by Company and Cofu and maybe also for minibuffer completion.

IIRC Stefan Kangas expressed similar desire on emacs-devel, though probably no work on that has been done yet.

OTOH, if I'm reading the nearby issue (41) right, you don't like VS Code's icons that we are using. So you might as well choose your own set, put it into Corfu, and then leave whatever possible unification to more distant future.

**Comment by minad** [comment]
> OTOH, if I'm reading the nearby issue (41) right, you don't like VS Code's icons that we are using. 

I am not a big fan, I find them a bit meaningless. But at least the icon set is quite comprehensive and consistent. If one goes with a separate package it would be good to have multiple icon sets to choose from. But vscode is a good starting point in any case.

> So you might as well choose your own set, put it into Corfu, and then leave whatever possible unification to more distant future.

Adding icons to Corfu directly is out of the question. I want a separate package - which can then be used to add icons to files (e.g. in dired), to completion candidates in the minibuffer based on the completion category and to completion candidates in the capf popup based on company-kind.

**Comment by dgutov** [comment]
All right. I'd like that too.

**Comment by minad** [comment]
Okay, let's see if we can pull something off - @jdtsmith is also interested in this.

**Comment by astoff** [comment]
I get issues with very long annotations:

![image](https://user-images.githubusercontent.com/6500902/156942652-6c399f56-3931-489e-b3c3-eb7d24d093d2.png)

I believe what's going on here is that the annotations are in fact right aligned, but the “Knudsen” one is very long and this pushes everyone else off of the pop to the right.

**Comment by minad** [comment]
I think this issue should be fixed. Please check the development first or check the old issues.

**Comment by astoff** [comment]
Indeed; sorry for the noise.
