### ISSUE TITLE
What is "TAB" completion?

### ISSUE THREAD

**Issue by trev-dev** [minad/corfu#200]
I have `(setq tab-always-indent 'complete)` and completions do not pop up unless I go M-TAB.

The documentation states that you can explicitly call a box by pressing `TAB` in a few spots, but also says that completion-at-point is `M-TAB`.

The meta key clashes with "Alt-Tab" as well as with my modal editing of choice (Meow). Am I goofy here, or is something I've configured being goofy, instead?

**Comment by trev-dev** [comment]
Got it! At some point in ancient history, I decided that binding "C-i" to "indent-relative" was a good idea. This seems to disrupt what my TAB key does.

**Comment by trev-dev** [comment]
I take it back. The "TAB" key works super inconsistently while looking for completions. I almost always have to use C-M-i (M-<TAB>). It's probably inconsistent enough for me to feel the need to not use <TAB> in the hopes of finding a completion. It largely depends on which completion back-end is doing the work.

For example, cape-file and cape-sgml often refuse to complete with tab.

Turning `(corfu-auto t)` causes completion to spontaneously pop up in better context than tab (manual) completion does, which feels unfortunate, as I don't really want to bind a special binding for each cape just to make sure I get the completion context I want.

**Comment by minad** [comment]
TAB or M-TAB is usually bound to completion-at-point. The TAB key is also overloaded with indentation, see tab-always-indent, which is see in the example config.

For more background read the Emacs manual or see https://emacsredux.com/blog/2016/01/31/use-tab-to-indent-or-complete/

**Comment by minad** [comment]
> For example, cape-file and cape-sgml often refuse to complete with tab.

I recommend to use explicit keys for completing special things like sgml entities. I also recommend to not deviate from the example configurations except if you are sure about the implications.

**Comment by trev-dev** [comment]
Thanks @minad! I had definitely read the docs and set tab-always-indent to 'complete. It sometimes feels like where thing should complete but find no results, or `dabbrev` steps in and populates the results. 

More desired results do fire up automatically in corfu-auto, but I think this is because the sequence of complete functions are just firing more often and churning the results when other completion back-ends respond.

Where TAB was not working I tried just interactively calling `cape-xyz` (like cape-ispell or cape-file`) and I'd get "No completion results" in areas where I felt like TAB should at least try to find something, such as completing in the middle of writing a word, inside a normal .txt document:

I subm| issues it on github
(M-x cape-ispell) => subm does not complete, or suggest to "submit".

Or while in the root directory:

Docu|
(M-x cape-file) => Cannot complete "Documents"

Maybe each completion requires some understanding of what they expect for input. In the HTML context, between strings, cape-file worked really well!

**Comment by minad** [comment]
> Where TAB was not working I tried just interactively calling...

* `subm| C-c p i` works for me. This triggers `cape-ispell`. `cape-dict` works too. Maybe your ispell setup has some issues.

* `Docu| C-c p f` works for me. This triggers `cape-file`. However if you use `cape-file` as Capf and trigger it via `completion-at-point` (TAB) it will be more defensive and bail out if you don't prefix the path with an existing directory, see `cape-file-directory-must-exist`.

> Maybe each completion requires some understanding of what they expect for input.

Yes, some understanding or experience is needed. We should probably improve the documentation of the Capfs. But who reads documentation? The docstring of `cape-file` refers to `cape-file-directory-must-exist`.

Of course it would be even better if all the functions would just behave out of the box as one would wish for. However for users who want that, a pre-made configuration is probably better, since many of the integration issues have been sorted out. Anyway if you have concrete well-thought-out proposals for how the out-of-the-box behavior could be improved I am all ears.

If Emacs is treated as Emacs and we want to configure it all ourselves, then there is no way around reading the doc strings and sometimes also reading the source. Cape is actually a good package where this applies, since it provides just a bunch of relatively simple isolated completion functions. The Capfs are also a good starting point in case you want to write your own custom completer.

**Comment by trev-dev** [comment]
Yeah, I have no proposals for you. I like the way Cape/Corfu work :) - they seem simple and easy to follow. I just wanted to get a better understanding of what's supposed to happen when you hit "tab" vs calling a cape interactively, or how these various cape CAPFs are supposed to interact in context. 

I can definitely see why the example config for manual completion has 1 or 2 capfs in the completion list, and so many prefix'd keybinds. These answers are good enough for me.
