### ISSUE TITLE
Completion in org-edit-special (C-c ')  doesn't seem to work

### ISSUE THREAD

**Issue by jgarte** [minad/corfu#203]
Hi does completion in org-edit-special (C-c ') work for anyone with `corfu`?

I was trying to autocomplete some python code in a org-edit-special buffer (babel) with eglot and pylsp turned on but it doesn't complete.

https://stackoverflow.com/questions/14704077/how-to-enable-auto-complete-in-emacs-org-babel

**Comment by Eason0210** [comment]
eglot not support `org-babel `yet.

https://github.com/joaotavora/eglot/issues/216

**Comment by minad** [comment]
It works for elisp blocks, when editing via `C-c '` `#+begin_src emacs-lisp ...`. This is not a Corfu issue, but rather a configuration or backend issue.

**Comment by minad** [comment]
Btw, you could give polymode a try, which may work with LSP servers since it maintains multiple buffers of the same file in different modes. Then you don't even have to switch to the separate special buffer. However I haven't tried polymode for a long time and back then it seemed a bit brittle.

**Comment by jgarte** [comment]
> eglot not support `org-babel `yet.
> 
> [joaotavora/eglot#216](https://github.com/joaotavora/eglot/issues/216)

Unrelated to corfu, but should eglot support tempel properly? I see it has support for yasnippet

**Comment by jgarte** [comment]
minad, thanks for the advice! I'll do some more testing/hacking

**Comment by minad** [comment]
> Unrelated to corfu, but should eglot support tempel properly? I see it has support for yasnippet

I think you will have a hard time convincing the eglot author to support something else. But I am sure that it is possible to hack in support via some advices.

**Comment by jgarte** [comment]
First I have to understand what the yasnippet feature in eglot exactly does. I haven't tried it yet.

**Comment by jgarte** [comment]
A fork of eglot with tempel support instead of yasnippet might be cool but maybe that's not necessary because of emacs advices...

**Comment by minad** [comment]
The way to go would be a separate integration package tempel-eglot.

**Comment by jgarte** [comment]
Cool, kind of like [consult-eglot](https://github.com/mohkale/consult-eglot) .

**Comment by jgarte** [comment]
I started collecting tempel snippets for python here:

Very much a WIP: https://git.sr.ht/~whereiseveryone/dot/tree/master/item/snippets

And I have tempel snippets I haven't pushed yet locally and/or ones that contain company code that I can't push but make work easier.

minad, thanks for making tempel. I love the hackability of the package.

Still trying to learn the tempo language. There's parts of the mini language that I still haven't grasped yet like `r` or `r>`, and others. Maybe I should just write snippets with those and see what they do to better understand how it works ;()

I'd love to have a way to convert arbitrary pieces of code into a tempel snippets by selecting a region in normal mode (evil) and converting it to a base tempel snippet/template. This would make it quicker to hoard/collect all the snippets I think I may need as I read through/come across code in the wild.

**Comment by jdtsmith** [comment]
This is not a corfu issue at all, and is actually quite challenging.  Polymode has gotten closest, and its ideas could be used.  

That said, there is a straightforward if complex way to build something into/alongside org which would do this: 

##Buffer per block

- For each (visited) src block, spawn an indirect clone buffer, narrowed to the block's contents and put in the appropriate mode for that language (org already handles that).
- Maintain and update that pool of hidden clone buffers, ensuring block boundaries are preserved and removing buffers whose parent blocks have disappeared or been merged.
- Since text properties are universal, fontification now "just works" (though you obviously need `font-lock-dont-widen=t`).  No need to copy properties back and forth as org does now. 
- You need some unique way to number/name the blocks, and the ability to store that information, possibly as text properties via the `org-element` API.

## Completion

- Create an `org-babel-completion-at-point-function` function.
- It examines the current position using the `org-element` API.  
- If it is inside a known block with a known clone buffer position, it performs completion using another regular configured completion function in the appropriate clone buffer.
- Completion results are presented in the org buffer.

None of these steps are easy.  But I know they work, since I've achieved this for the case of a singular "block" (text after prompt in a REPL).
