### ISSUE TITLE
Option to preview top candidate without popup

### ISSUE THREAD

**Issue by meain** [minad/corfu#211]
Company had an option to preview the top candidate in the buffer without opening a popup. In most cases, this is all I need and don't actually need the popup to show up; but if I need the all the options, I can just wait some more time and get it. This was much less intrusive in most cases where I just want to complete some long name that I know it will be the top candidate or I have completed this thing before and is in the top of my history or I know what exactly to prefix to get it. Is there some way I can recreate this with corfu?

https://user-images.githubusercontent.com/14259816/182438320-81c16679-6cc9-4d1a-b406-bf484373bef4.mp4

**Comment by minad** [comment]
No, this feature doesn't exist yet in Corfu. I've considered before to add it but so far I've got along just fine without it. The reason is that previewing the top candidate does not generalize well. It only works well with prefix completion (the basic completion style), where the input matches the prefix of the candidate. I am a fan of non-prefix completion (orderless, substring, regexp, flex). For non-prefix completion the input doesn't match the candidate prefix and the preview of the topmost candidate is not possible, since the preview overlay would have to overwrite the entire input.

Anyway I am not opposed to adding this feature if someone is interested in implementing it.

**Comment by meain** [comment]
Just for anyone running into this in the future, https://code.bsdgeek.org/adam/corfu-candidate-overlay/ seems to be doing something similar.
