### ISSUE TITLE
The completion menu is not displayed, but the candidates are printed in the buffer

### ISSUE THREAD

**Issue by twlz0ne** [minad/corfu#212]
![Screenshot_2022-08-04_at_12 46 28_PM__Emacs-corfu-elpl-issue](https://user-images.githubusercontent.com/2653486/182765856-285357f6-8ee2-4914-84da-795e4f6fd7b4.png)

### Actual behavior

Candidates are printed in buffer.

### Expected Behavior

Display completion menu.

### Steps to reproduce

0. Pre-installation:

   ```sh
   pip install keyboard
   git clone https://github.com/minad/corfu ~/repos/emacs-corfu
   git clone https://github.com/twlz0ne/elpl ~/repos/emacs-elpl
   ```

1. Launch Emacs:

    ```sh
    emacs -Q --eval "
    (progn
      (add-to-list 'load-path \"~/repos/emacs-elpl\")
      (require 'elpl)

      (add-to-list 'load-path \"~/repos/emacs-corfu\")
      (require 'corfu)
      (setq corfu-auto t)
      (global-corfu-mode)

      (elpl))"
    ```

2. `M-x async-shell-command` execute following command:

    ```sh
    python -c '
    import time
    import keyboard
    CORFU_DELAY = 0.21
    keyboard.press_and_release("g")
    time.sleep(CORFU_DELAY)
    keyboard.press_and_release("l")
    time.sleep(CORFU_DELAY)
    keyboard.press_and_release("o")
    '
    ```

3. `M-<backspace>` delete input if completion menu is displayed.

4. Repeat step 2.

### System information

- macOS 10.13.6
- Emacs 27.2 & 28.1 & 29.0
- Packages:
    + corfu [49a7a6e](https://github.com/minad/corfu/commit/49a7a6e2dc8c400400d34b77ebc5709f458af88f) (2022-07-28)
    + elpl [501871a](https://github.com/twlz0ne/elpl/commit/501871ab543b9967bfe87a8a82f83ab96b7f909e) (2022-03-28)

**Comment by twlz0ne** [comment]
The following modification can avoid the issue in this case:

```diff
$ git --no-pager diff --no-color
diff --git a/corfu.el b/corfu.el
index 83e7ce0..f31ad2b 100644
--- a/corfu.el
+++ b/corfu.el
@@ -1180,7 +1180,7 @@ (defun corfu--auto-complete-deferred (&optional tick)
   (setq corfu--auto-timer nil)
   (when (and (not completion-in-region-mode)
              (or (not tick) (equal tick (corfu--auto-tick))))
-    (pcase (while-no-input ;; Interruptible capf query
+    (pcase (progn
              (run-hook-wrapped 'completion-at-point-functions #'corfu--capf-wrapper))
       (`(,fun ,beg ,end ,table . ,plist)
        (let ((completion-in-region-mode-predicate

**Comment by minad** [comment]
Thanks for the report! You can work around this issue by wrapping your Capf with a non-interruptible wrapper:

~~~ elisp
(advice-add #'elpl-completion-at-point :around '#cape-wrap-noninterruptible)
~~~

But I strongly suggest that you try to make your Capf more robust against interruption, since this is the only way we can achieve good responsiveness with Corfu. Also interruptibility is a good property for any kind of operation since the user could always hit C-g. You probably didn't observe this issue before since Company doesn't interrupt Capfs or completion tables. In contrast, Icomplete and Vertico interrupt tables, but are not used as often with `completion-at-point`.

Also note that the docstring of `completion-at-point-functions` says the following:

~~~ elisp
NOTE: These functions should be cheap to run since they're sometimes
run from post-command-hook; and they should ideally only choose
which kind of completion table to use, and not pre-filter it based
on the current text between START and END (e.g., they should not
obey completion-styles).
~~~

This means that the Capf itself should ideally be pure and fast. The Capf should return a completion table which then performs the actual completion based on the input. But again, the returned completion table should be interruptible.

See also #102, #151 and #188.

**Comment by twlz0ne** [comment]
Thank your for the suggestion.
