### ISSUE TITLE
Lisp error: `(args-out-of-range "" 1 nil)`

### ISSUE THREAD

**Issue by cordelia04m** [minad/corfu#216]
![corfu](https://user-images.githubusercontent.com/48050400/184277465-ee94f8c5-b3a2-4a2c-910d-7c9c0e6306b4.png)

Emacs 28.1  
Corfu 0.26
Org 9.5.4

Sorry for posting a screenshot, but the backtrace buffer disappeared when I selected it.

The error happened when I was using org-mode and pressing the spacebar to separate words I type. Reactivating corfu-mode didn't solve the error. 

I think that's too little info to track down the error, but it came out of nowhere. I also experienced other errors that randomly happen here and there, is there a way to dump Emacs states or something like that to help you to track down the errors?

**Comment by minad** [comment]
Such errors are backend issues, in this case of pcomplete-completions-at-point and should be reported via report-emacs-bug or via the org ml. Ideally the bug is reproduced without Corfu on emacs -Q.

The pcomplete backend is notoriously buggy. On Emacs 28 I recommend to use Cape advices as workarounds. See https://github.com/minad/corfu#completing-in-the-eshell-or-shell for the configuration. Please let me know if this resolves the issue.

**Comment by cordelia04m** [comment]
Thanks. I'll try those snippets.
