### ISSUE TITLE
typing speed and rhythm seems to affect behaviour

### ISSUE THREAD

**Issue by ville-h** [minad/corfu#227]
Typing speed and rythm seems to affect behaviour. As a test case I used the stem "std::en" and the snippet:
```
#include "iostream"


auto main() -> int {
    // the goal is to complete to "std::endl" by typing "std::en" using varying typing speed and rhythm
    // on the line below:
    
    return 0;
}
```
The offered completions may differ for the same "stem" or there might be no completions offered at all depending how exactly it was typed. The inconsistent behaviour is not limited to just "std::en".

How do I fix this so that it I get predictable behaviour no matter what speed and rythm I am typing at? I am using [this coniguration](https://github.com/minad/corfu/wiki#basic-example-configuration-with-orderless).

**Comment by minad** [comment]
Please ask about this issue on the lsp-mode issue tracker, since it is purely a backend issue (lsp-mode Capf).

**Comment by minad** [comment]
A few hints which may be helpful to debug this:

1. Look at the lsp logs to see the data received from the server. Do you observe the inconsistency there?
2. Try a minimal configuration with the `flex` completion style, since this style lets more candidates pass. See https://github.com/minad/corfu/wiki#example-configuration-with-flex.
3. Guard the lsp-mode Capf against interrupts. Your issue sounds as if this could lead to inconsistencies. Unfortunately the current lsp-mode Capf is not yet interruptible. See https://github.com/minad/corfu/issues/188 and https://github.com/emacs-lsp/lsp-mode/issues/3555.

~~~ elisp
(advice-add #'lsp-completion-at-point :around #'cape-wrap-noninterruptible)
~~~
