### ISSUE TITLE
`dabbrev` completions not showing up

### ISSUE THREAD

**Issue by kenranunderscore** [minad/corfu#233]
I've typed the following simple Haskell code into a scratch buffer with `haskell-mode` enabled:

```haskell
data FooBar = FooBarBaz
  { fooBlub :: Int
  }
  deriving stock (Eq, Show, Generic)

FooB[cursor here]
```

Using `corfu` with `corfu-auto` enabled, and also `cape` with `(add-to-list 'completion-at-point-functions #'cape-dabbrev)`, I'd expect a `corfu` popup to show up at the cursor position. Invoking `cape-dabbrev` manually I get the popup containing `FooBar` and `FooBarBaz`.

I guess I'm just misunderstanding or misusing something, as I sometimes do see what looks like `dabbrev` completions in the popup. I just don't know what it is :) Let me know if this issue/question is a better fit for the `cape` repo, then I'll open it there. Thanks!

**Comment by kenranunderscore** [comment]
It might be related to #171 that I just found. I don't quite grasp that one either, but I'll have a longer look.
I'll close this for now, as I just saw that `completion-at-point-functions` does not contain the `cape` ones I added, so there might be something wrong with my config.

**Comment by kenranunderscore** [comment]
I guess https://github.com/minad/cape/issues/53 is the more likely candidate (the default Haskell capfs are probably similar to the Elisp one) and explains an aspect I didn't understand yet.

**Comment by OzzyNeto** [comment]
@kenranunderscore How did you go about solving this? I'm having the same issue.

**Comment by kenranunderscore** [comment]
@OzzyNeto I've copied some stuff from other issues here and in the `cape` repository. You can see my config here:
 https://github.com/kenranunderscore/dotfiles/blob/main/home-manager-modules/programs/emacs/emacs.d/config.org#L1619

The solution for modes other than Elisp is a little crude, as I'm just adding the cape backends to the front of the local alist, but it's enough for my Haskell use case.

**Comment by minad** [comment]
@OzzyNeto @kenranunderscore Yes, the completion-at-point-functions must be tweaked per mode. This is a bit of a hassle but also gives you tons of flexibility. You should always check the value of this variable in a buffer.

**Comment by OzzyNeto** [comment]
@kenranunderscore @minad Worked for me, thank you so much!

**Comment by LensPlaysGames** [comment]
I'm running into what may be a similar issue? Dabbrev expansions are not showing up in some cases.

For example, I have a buffer like so
```
reject

[cursor here]
```

When I type `rej`, I expect `reject` to be a completion candidate, but no match shows up. If I manually call `dabbrev-completion`, `reject` is inserted, as expected. So `dabbrev` *seems* to be aware of this completion and is able to complete it. However, if I call `cape-dabbrev` manually, then I get a message in the echo area describing how there are no completions available. How can I fix this?

**Comment by minad** [comment]
@LensPlaysGames Try these settings. `cape-dabbrev-min-length` exists mainly to avoid over eager auto completion, but I should probably remove this feature since it is not that great. Such candidate length restrictions should be better handled on the level of the completion tyle.

~~~ elisp
(setq cape-dabbrev-min-length 0
      cape-dabbrev-check-other-buffers nil)
~~~

**Comment by minad** [comment]
> (imo stupidly)

You should first learn how these things work before judging. A small limit may lead to many unnecessary candidates during auto completion. You can probably type four characters quickly enough that you don't want to see candidates with less than four additional letters offered for completion. Unfortunately the behavior is not that great and I am also not happy with it, but mainly since the behavior should be uniform across similar backends (cape-dabbrev and cape-dict for example).

> It seems like I can only get one backend's completions to show at one time

Yes, read the manual.

**Comment by LensPlaysGames** [comment]
> You should first learn how these things work before judging.

That's fair. I may have been too harsh due to my frustration, so I apologise if that felt rude. You are right that most people probably wouldn't mind the 4-character limit, and it is probably unique to my use case to need such aggressive dabbrev completions.

> Yes, read the manual.

I have read the entire README, but still haven't found anything regarding this "single backend" thing. I have seen the "exclusivity" property in Emacs' `completion-at-point-functions`; do I need to set that for every backend manually (i.e. using `cape-capf-nonexclusive` or something?)

**Comment by minad** [comment]
Yes, thanks. It was rude. I try to be helpful here and I find unnecessary negativity disappointing. Yes, Emacs can be frustrating. I would not recommend it to anyone who just wants something which works. Emacs shines only if you hack it.

> I have read the entire README, but still haven't found anything regarding this "single backend" thing.

This design is certainly mentioned in the Emacs manual and also in the Cape manual, see for example `cape-super-capf`.

**Comment by LensPlaysGames** [comment]
Well, it may be necessary to make that part of the manual more prevalent or easier to find? I can't find anywhere in the corfu Emacs info pages that mentions that the proper behaviour is that only one completion function's results will ever be shown?? It says it's minimal, it says it uses Emacs' built-in capf functionalities and that it doesn't provide it's own, but where does it talk at all about not showing multiple backends completions at once?

You are right that in the `cape` README/manual it *does* go over this, specifically in the `cape-super-capf` section: <https://github.com/minad/cape#super-capf---merging-multiple-capfs>. I still think that this isn't really a solution. How would one meaningfully configure per-mode completion functions? It would be a mess of needing a specific "super" function for every single major mode that may have different completion functions necessary.

Anyway, thanks for your time, I guess.
