### ISSUE TITLE
Advising Corfu to Work with Emacspeak?

### ISSUE THREAD

**Issue by hjozwiak** [minad/corfu#236]
## Problem Statement

When using Corfu, Emacspeak does not speak items that appear as completion candidates. It does, given the correct duration, speak the documentation string for the currently selected candidate. If, for example I go into a scratch buffer and say (whe and move through the candidates, I get docstrings for when, when-let, and whatever else happens to start with that prefix.

## Attempt

I had attempted to advise some of the interactive commands to get Emacspeak to speak the candidates; here is what I have going so far:

``` elisp
(use-package corfu
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-auto-delay 0.0)
  (corfu-auto-prefix 2)
  :preface
  ;; Set up some voice mappings
  (voice-setup-add-map
   '(
     (corfu-current voice-bolden-and-animate)
     (corfu-annotations voice-animate)
     (corfu-deprecated voice-monotone)
     (corfu-echo voice-bolden)))
  (defun ems-corfu-current-selection ()
    "Return the currently selected candidate."
    (cl-declare (special corfu--index corfu--candidates))
    (nth corfu--index corfu--candidates))

  (defun emacspeak-corfu-speak-this (&optional _n)
    "Speak the current selection"
    (ems-with-messages-silenced
      ;; Do we have any metadata to speak of?
      (when corfu--metadata
        (propertize corfu--metadata 'personality 'voice-annotate)
        (dtk-speak-and-echo
         (concat (ems-corfu-current-selection) " " corfu--metadata)))))
  :config
  (cl-loop for f being the elements of '(corfu-next corfu-previous) do
           (advice-add f :after #'emacspeak-corfu-speak-this)))
```

## Inquiries

* Is there an easier way to do this, i.e. a hook to leverage?
* If not, how do I learn what the metadata represents? I had tried to debug watch the variable, but those efforts proved unfruitful.

Thanks,

Hunter

**Comment by minad** [comment]
Unfortunately I am not familiar with Emacspeak, so you may get a better answer from the author of Emacspeak. I wonder what mechanism Emacspeak uses usually to hook in its speech output. It seems to me that a post-command-hook would work well, where this-command is checked. But using an advice as you do here also seems like a good solution.

The metadata is used wrongly in your snippet above, since it is an alist of completion metadata and not a string. The metadata is an extensible mechanism to provide additional information for the completion candidates or to specify sorting. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html. The completion metadata provides for example the annotation-function, see https://github.com/minad/corfu/blob/3490a42c30e4e32fe2d76dfc7736b649d37950db/corfu.el#L710.

**Comment by minad** [comment]
I forgot to mention that you should also check Emacspeak support for Company. If supported, you could probably port over the support from there.
