### ISSUE TITLE
Prefer vertico over corfu in some cases/modes

### ISSUE THREAD

**Issue by timlod** [minad/corfu#237]
Hey,
First of all, thanks for both these packages :)
Not sure if this is more appropriate over at vertico or here, but I'm not sure that matters too much.

I've switched over to vertico for minibuffer completion a while ago, and from company to corfu recently.
One thing I noticed is that another package I use a lot, `emacs-jupyter` seems to have a bug which causes issues with auto-completion frameworks of the popup kind (https://github.com/nnicandro/emacs-jupyter/issues/323).
This lead me to turn off company-mode in `jupyter-repl-mode` - turns out that I then had `vertico` completion available in the REPL, without the bug I linked - great!

However, `(setq corfu-excluded-modes '(jupyter-repl-mode))` does not work the same way - vertico does not activate in `jupyter-repl-mode` even if I don't use corfu there.

Is there a way to normally use corfu for in-buffer-completion, but vertico in others?

**Comment by minad** [comment]
Thanks!

You can use vertico+consult-completion-in-region for in-buffer completion in some buffers. Just set the completion-in-region to consult-completion-in-region locally. Then enable corfu-mode in other buffers where you prefer Corfu. Note that corfu-mode is already a local mode. Alternatively you can use global-corfu-mode and configure the excluded modes. It seems you already tried that? Did you investigate why Corfu was still turned on in the jupyter buffers despite being excluded?

I hope this helps. I am usually not investigating special integration issues since this would exceed my time budget. Nevertheless it would be very useful if you start with an emacs -Q config and create a minimal setup which demonstrates the issue. Then we can investigate from there.

**Comment by timlod** [comment]
Thanks - the fix turned out to be simple (sorry for the half-baked issue, I understand why those are too much to look into)!

For reference, if anyone else is wondering the same:
I already had 
```elisp
(setq completion-in-region-function
      (lambda (&rest args)
        (apply (if vertico-mode
                   #'consult-completion-in-region
                 #'completion--in-region)
               args)))
```
in my config, along with `global-corfu-mode` and the excluded mode - however, `completion-in-region-function` does not stay set in excluded modes (at least in the jupyter repl) that way.

Changing to `setq-default` on the `completion-in-region-function` made it work - now we have `corfu--in-region` in all modes except for vertico+consult in the `jupyter-repl`.
