### ISSUE TITLE
Supporting `corfu-popupinfo` in terminal

### ISSUE THREAD

**Issue by AkibAzmain** [minad/corfu#248]
I have tried `corfu-docframe` and it works well.  I would like to support it in terminal.  The code looks much saner than its predecessor `corfu-doc` package, and I think it should be possible to do this with about 3-5 advices if `corfu-docframe` is refactored properly.  My suggestions are:

- Split `corfu-docframe--show` into two parts, one child-dependent, and other one independent, so that I can override the child-dependent part.
- Split `corfu-docframe-scroll-up` into two part as above, it's saner to advice plain function than interactive commands.

What do you think, @minad?

**Comment by minad** [comment]
@AkibAzmain Sure. Note that the extension is still undergoing heavy churn. As you probably saw, I even renamed it again to reflect that the extension supports previewing both the candidate location and the candidate documentation.

To not get your hopes up too quickly - I had to put quite a lot of work into the extension and I would like to let it rest for a while as is. I also want to await some user feedback. 

Probably I can return to this extension around Feb 2023. In the meantime, if you could get the assignment it would be great! I've seen that you've been trying to get it but unfortunately hit some unpredictable obstacles.

**Comment by AkibAzmain** [comment]
`corfu-infoframe` looks to hot to touch, I think I should came back to this after a while when it cools down.

**Comment by minad** [comment]
Renamed the extension again :rofl:

**Comment by AkibAzmain** [comment]
What's going on??? :dizzy:

**Comment by minad** [comment]
I couldn't help myself. I just wasn't happy with the choice we've made before. But now I like corfu-popupinfo. It emphasizes the popup and has info in the name like the older corfu-info.

**Comment by dalugm** [comment]
Why not call it `corfu-popup`?

https://github.com/minad/corfu/blob/536b68b733ce1912c5ed97c9054fb42ef7957b39/extensions/corfu-echo.el#L1

https://github.com/minad/corfu/blob/536b68b733ce1912c5ed97c9054fb42ef7957b39/extensions/corfu-info.el#L1

https://github.com/minad/corfu/blob/536b68b733ce1912c5ed97c9054fb42ef7957b39/extensions/corfu-popupinfo.el#L1

These three extensions show information about candidates, but they don't have a unified name style. And according to current situation, I don't think `corfu-info` is a good name, it seems like `corfu-popupinfo` has a dependency on it.

How about calling them `corfu-echo` `corfu-buffer` `corfu-popup` for simple, or `corfu-echo-info` `corfu-buffer-info` `corfu-popup-info` for details.

**Comment by minad** [comment]
@dalugm corfu-buffer and corfu-popup are meaningless. corfu-buffer-info and corfu-popup-info feel too long, in particular the two dashes lead to ugly command names. I will stick to the current names for now, waiting for better suggestions. What about corfu-info -> corfu-sideinfo, but side is maybe too generic?

**Comment by dalugm** [comment]
> side is maybe too generic?

`corfu-sideinfo` is a good idea, side is maybe too generic as you say, but it has a `info` as a suffix I think is not a big problem. 

Have you considered `corfu-bufferinfo`? Because it will always open a buffer to show information, just like `corfu-popupinfo` will always open a popup. But it's longer than side, which is somehow unapposite.

**Comment by dalugm** [comment]
> side is maybe too generic?

`corfu-sideinfo` is a good idea, side is maybe too generic as you say, but it has a `info` as a suffix I think is not a big problem. 

Have you considered `corfu-bufferinfo`? Because it will always open a buffer to show information, just like `corfu-popupinfo` will always open a popup. But it's longer than side, which is somehow unapposite.

**Comment by minad** [comment]
On 11/19/22 07:29, dalu wrote:
>     side is maybe too generic?
> 
> |corfu-sideinfo| is a good idea, side is maybe too generic as you say,
> but it has a |info| as a suffix I think is not a big problem.
> 
> Have you considered |corfu-bufferinfo|? Because it will always open a
> buffer to show information, just like |corfu-popupinfo| will always open
> a popup. But it's longer than side, which is somehow unapposite.

For some reason I don't like bufferinfo. I cannot really pin it down,
maybe it is slightly too long, maybe it looks to be as we are showing
some info about buffers (like ibuffer, buffer-list, ...). Note that
corfu-info has been there before the merge of corfu-doc. That's the
reason why we still have this name. The nem of corfu-doc went through so
many changes since I also generalized it to show both documentation and
the source of the candidate.

**Comment by dalugm** [comment]
> I cannot really pin it down
>
>  That's the reason why we still have this name

I understand, since `corfu-info` had kept its name for quite a while and `corfu-popupinfo` is in a big change right now, it may be unwise to determine their names at this time. But as the README says: 

https://github.com/minad/corfu/blob/536b68b733ce1912c5ed97c9054fb42ef7957b39/README.org?plain=1#L445-L446

I just thought the `corfu-info`'s name is no longer suited for now and it has to be changed. Now I can see it that you already had a plan in mind, hope to see it stable soon ;)

---

ps: Sorry to talk about so many topics unrelated to `corfu-popupinfo` in terminal at this issue, I hope it doesn't affect your work much

**Comment by AkibAzmain** [comment]
Well, then, I've another name in mind, `corfu-popdoc`.

**Comment by AkibAzmain** [comment]
> ps: Sorry to talk about so many topics unrelated to corfu-popupinfo in terminal at this issue, I hope it doesn't affect your work much

@dalugm That's won't affect me, because I will start doing this after the extension activity cools down.  (It is too hot to touch now.  ;-) )

**Comment by AkibAzmain** [comment]
> I also generalized it to show both documentation and the source of the candidate.

I've tried it yet, but it's indeed a nice addition, source code is the best documentation.

**Comment by AkibAzmain** [comment]
Now that the `corfu-doc` package is deprecated, can you please do the requested changes?

**Comment by minad** [comment]
@AkibAzmain It seems that your timeline is flowing faster than mine, see https://github.com/minad/corfu/issues/248#issuecomment-1319816025. This won't happen any time soon. While corfu-popupinfo has stabilized, we still have to make some bigger changes (see #264). @galeo is working on that.

Btw, do you use Emacs on the terminal? I've seen you implemented your own Emacs terminal emulator, which kind of suggests that you use GUI Emacs. Therefore I wonder why Corfu terminal support is so important for you. For me it is not a priority.

**Comment by AkibAzmain** [comment]
No, I'm not from the future, and I also don't have a time-machine.  (But when I have (or discover, super unlikely) one, I'll sure write an Emacs package for time traveling.)

BTW, thanks for notifying me about #264, I'll keep an eye on it.

> I've seen you implemented your own Emacs terminal emulator, which kind of suggests that you use GUI Emacs.

I do use terminal, sometimes for distraction less environment, and sometimes to fix broken EXWM (yes, I break it sometimes.)  Whatever UI (GUI or TUI) I am using, I need terminal emulation _inside_ Emacs.  However this time the main reason for asking you again is that someone asked me on Fediverse what will happen to `corfu-doc-terminal`  as `corfu-doc` is obsolete.

**Comment by minad** [comment]
Isn't it clear what will happen? We will fix this such that you can hook in with corfu-terminal. But it will take its time, such that everything has stabilized sufficiently. I also have to wait for feedback, since this could imply additional changes. The estimate I've given seems realistic.

**Comment by minad** [comment]
Regarding the terminal and fixing things in the init.el - I assume that you don't need Corfu there. So I don't really buy this argument. ;)

I am not an EXWM user, but for a while I also had a minimal.el config separate from my main config for fixing. But nowadays my config is just robust enough and I could kick the minimal one out. I also compile my config and all the custom libs and there is flymake package linting in place. I almost never have the situation where Emacs cannot boot. :)

**Comment by the42** [comment]
Deciding if I should subscribe to this bug./request I read through the comments but can't make a final clue. Is this meant to integrate https://codeberg.org/akib/emacs-corfu-terminal into corfu so corfu works out of the box on terminal too?

Or is emacs-corfu-terminal meant to stay? It doesn't get clearer with https://codeberg.org/akib/emacs-corfu-terminal/issues/16

**Comment by minad** [comment]
@the42 corfu-terminal will stay a separate package because of licensing issues and because it has a separate dependency. But corfu-terminal may also support corfu-popupinfo in the future.

**Comment by AkibAzmain** [comment]
> Probably I can return to this extension around Feb 2023

I'm damn sure its already February 2023 all over the world.

**Comment by minad** [comment]
@AkibAzmain Yes. Unfortunately I cannot implement this any time soon, since I personally don't need this feature. I was quite involved in Emacs package development recently, in particular with the Compat package, which is a priority for me. I have to slow down a bit again for the next months due to time constraints. If you really want the corfu-popupinfo terminal feature, please provide a patch. And yes, it still requires the copyright assignment. This would save me all the work and we would have the feature very soon.

Regarding this discussion - I must explicitly ask you to not write in a "demanding style", I mean the "I'm damn sure" part. I don't owe you that this gets implemented and I don't owe you any of my time. Also I did not make any promises. I understand that you really want to have this feature and that you are enthusiastic about it. But please be patient. I also think that corfu-popupinfo terminal support would be nice to have, but it is not a priority for me. If it is a priority for someone, I am open to discuss [sponsoring](https://github.com/sponsors/minad) options, but that is all I could possibly offer.

**Comment by AkibAzmain** [comment]
> I must explicitly ask you to not write in a "demanding style", I mean the "I'm damn sure" part.

I'm sorry, I didn't want to hurt you.  Anyway, thanks for pointing out the mistake, you saved me from repeating it somewhere else.  I just wanted to remind you, nothing more.  I'm also pretty busy now, so it's also hard to me even to try implement this.

**Comment by minad** [comment]
@AkibAzmain

Thanks. In general please don't ever demand anything from foss maintainers. This is a major cause for maintainers to give up and close their issue trackers. Most already do their work for free. They also usually don't need reminders. It is assuming of you that they do. The issue tracker already is reminder enough. Note that we are not talking about a major flaw or security issue here. If I look at my issue trackers, they are quite empty given the amount of usage seen by my packages. If you still want to ask if there is progress, which you can do of course, please do it in a friendly non-demanding way. Not as if they should have already done what you've asked for. Usually this won't be seen negatively. Also don't ask immediately on the 02-02 if the potential time frame was February, but maybe a month later. When I read through this thread, it seems to me that I already reminded you multiple times to be less demanding and more patient (maybe not as clear as now), so please finally internalize that! There is one more thing - I've seen that you've created a number of interesting packages, which also seen some adoption now, e.g., Eat. But having written your own packages still does not give you the right to demand something from others. You may only be more demanding if you are actively collaborating on the same project, such that there is an equal give and take. But even then you should only do it if there is some common understanding.

**Comment by AkibAzmain** [comment]
@minad, I'm again saying that that I didn't mean that, apologies for the inconvenience.

> Also don't ask immediately on the 02-02 if the potential time frame was February, but maybe a month later.

Excuse me, what does that "02-02" mean?

> But having written your own packages still does not give you the right to demand something from others.

Exactly.  I do know much better than before how much effort it takes to implement a feature or fix a bug.

**Comment by minad** [comment]
@AkibAzmain It is okay. Please keep it in mind for the future.

> Excuse me, what does that "02-02" mean?

Today is the 2023-02-02. It is the beginning of February.

> Exactly. I do know much better than before how much effort it takes to implement a feature or fix a bug.

That's not even the biggest amount of work. The real work comes if many people start to adopt your packages. Then you will get bug reports for special edge cases, very special feature requests, and unfortunately even demands and insults.

**Comment by minad** [comment]
@AkibAzmain Btw, in https://github.com/minad/corfu/commit/beae37b96ba368e252ce9f9b8588768378953519 I moved away from advices to `cl-defgeneric`. We could use that too for `corfu--popup-show/hide` etc, such that you could hook in more cleanly. What do you think?

**Comment by AkibAzmain** [comment]
I really don't know much about the power of `cl-defgeneric`, but if they can replace advices, I guess that's good.

In that commit message,

> The recent discussion on emacs-devel made me reconsider advices again.

Which discussion?

**Comment by minad** [comment]
@AkibAzmain See for example https://github.com/minad/corfu/blob/a74f160c5b2210a6a3a4a13b1303b1ab2d36a334/extensions/corfu-popupinfo.el#L501.

The discussion about keymap-local-set on the bug tracker/emacs-devel. There were some arguments about advices and called-interactively-p which are better avoided if possible.

**Comment by Lenbok** [comment]
I've just switched from company to corfu (and since I'm a heavy terminal user, this has been allowed thanks to `corfu-terminal`). I'm wondering @AkibAzmain if you have made any progress updating `corfu-doc-terminal` to use the changes that @minad made to generify `corfu-popupinfo`?

**Comment by minad** [comment]
On 4/30/23 11:57, Len Trigg wrote:
> I've just switched from company to corfu (and since I'm a heavy terminal
> user, this has been allowed thanks to |corfu-terminal|). I'm wondering
> @AkibAzmain <https://github.com/AkibAzmain> if you have made any
> progress updating |corfu-doc-terminal| to use the changes that @minad
> <https://github.com/minad> made to generify |corfu-popupinfo|?

As far as I understand corfu-popupinfo still needs changes to support
corfu-terminal. @AkibAzmain unfortunately cannot assign copyright, which
is required for ELPA projects, and I seldom use Emacs on the terminal.
Emacs itself is my shell and terminal. Maybe someone else is interested
in contributing a patch to push this over the finish line?

**Comment by idlip** [comment]
Hello everyone, I'm not sure if you are familiar with [popup.el](https://github.com/auto-complete/popup-el)

 I discovered it by using sdcv an offline dictionary package, which has option to show dictionary string in popup. When i played with the choice, I saw that popup-tip (popup.el) was working in terminal also.
 
 
![popup-terminal](https://github.com/minad/corfu/assets/117019901/f010472d-bae1-4e96-942c-ec3ff2355abf)

From the function: `(popup-tip "string")`

Hopefully, it opens up the possibility for corfu-popupinfo in terminal!

Please ignore this if it has been known and the if I have misunderstood the issue.

Thank you for your work akib & minad, as always!

**Comment by minad** [comment]
@idlip Hi! The problem is not so much that we are lacking a library to implement the corfu-popupinfo display. We already have @AkibAzmain's popon, which is used by corfu-terminal. In order to support corfu-popupinfo on the terminal too, we have to do two things:

1. Make corfu-popupinfo more extensible, such that corfu-terminal can provide its own display implementation. For the Corfu candidate popup, this is achieved using `cl-defgeneric`  functions, which are overidden by corfu-terminal using `cl-defmethod`.

2. Add the popon-based implementation to corfu-terminal.

**Comment by minad** [comment]
I close this issue to not give a false impression, that this feature will land soon. For the reasons, see the bad example in https://github.com/minad/org-modern/issues/5. 

*To be clear, I welcome a patch which adds this feature!*

**Comment by LionyxML** [comment]
@AkibAzmain hey there!

So, long history short:
- corfu is added
- corfu-doc is added 
- corfu-doc-terminal is added

(for the first time in history, a modern completion system with built in help with modern looks happens in Emacs on both TUI and CLI, yey!)

- corfu-doc gets integrated within corfu
- https://github.com/galeo/corfu-doc/issues/18 << this discussion "hoping" TUI will be implemented
- corfu-doc-terminal is broken
- we are all sad

And this issue is closed Why?

Man I wish "Child frames" got into Emacs only with the condition to have a default "fallback" to some sort of popup. It is breaking GUI/TUI integration for A LOT of cool stuff, we always need to resource to an extension of an extension, and as one project goes on, making others compatible seems impossible.

Please @minad, take a kind new look into getting this feature (doc corfu) for terminal. Even if its not 100% compatible or even without extended controls.

Many people come from other TUI editors (like vim, neovim, ex), for this people, sometimes it is too much trouble move to GUI and to Emacs all in one environment all at once. They prefer stay inside tmux and have a try on emacs -nw.

For others like me, I use Emacs for almost everything, including tons of SSH sessions. And having the same User Experience on both GUI/TUI is killer when trying new packages, I even maintain a config with this in mind ( https://github.com/LionyxML/lemacs ), I'd love to integrate corfu into it.

So if you guys could hear my pledge, let's get Corfu 100% functional to GUI and TUI. Completion the "modern way" is one of the last barriers emacs TUI/GUI integration has.

Thanks! :)

**Comment by minad** [comment]
@LionyxML I think my last two comments were clear. I am happy to review patches which prepare corfu-popupinfo for corfu-terminal integration. Then Akib's corfu-terminal package can provide the alternative terminal-compatible display. Furthermore I am willing to accept an overlay-based corfu-terminal extension here (implemented via overlays). 

Ideally Emacs would provide some kind of popup/child frame implementation on terminal too. It doesn't have to be 100% compatible with child frames. The odd thing is that Emacs already comes with such a popup functionality in the form of `x-popup-menu`, which even works on `emacs -nw`. This means that Emacs already provides all that is needed for child frames on the level of the terminal display engine! Try this:

~~~ elisp
(x-popup-menu `((,(car (posn-x-y (posn-at-point (point))))
                 ,(+ 3 (cdr (posn-x-y (posn-at-point (point))))))
                ,(selected-frame))
              (easy-menu-create-menu
               "Testing"
               `(["some testing 1" next-line]
                 ["some testing 2" previous-line])))
~~~
