### ISSUE TITLE
Recent commits are incompatible with Emacs <29

### ISSUE THREAD

**Issue by jkroes** [minad/corfu#290]
[This commit](https://github.com/minad/corfu/commit/6081a68db6f74a493431d647942fc294964910aa) introduced `defvar-keymap`, which is only available from [keymap.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/keymap.el) in Emacs 29. When using Emacs 28, `global-corfu-mode` fails with an error about `void-variable corfu-map`.

**Comment by minad** [comment]
Corfu uses Compat.

**Comment by russmatney** [comment]
Thanks for the clue on this issue - compat looks very useful! It was indeed a package management problem.

If it helps anyone else, my issue was compat being pinned by doom (or otherwise not pulling the compat-29.el file), so unpinning meant pointing to github and setting a new pin, i.e. in `doom.d/packages.el`:

```
(package! compat :pin "e59e311d1ffc422f91e4e9c494598e978f5c2125"
          :recipe (:host github :repo "emacs-compat/compat"))
```

Hopefully it wasn't pinned for some specific reason.

**Comment by russmatney** [comment]
@minad gotcha - thanks for sharing the context!
