### ISSUE TITLE
[Proposal] Extend capf with a property :input-function to improve completing experience of LSP.

### ISSUE THREAD

**Issue by zbelial** [minad/corfu#292]
# Current situation
## How LSP completion works
Usually, three different attributes of completion items returned by LSP servers are used: label, insertText and textEdit.

If `textEdit` exists, clients should apply it to the document and ignore the other two. Otherwise, clients should insert `insertText`. The `label` is the last one to resort to.

The `textEdit` specifies the document range it will replace, and the content(called `newText` in LSP spec) that should be used as the replacement. Sometimes, `newText` is a snippet with the same grammar as `yasnippet`.

## How LSP clients(eglot/lsp-mode) completes
Eglot and lsp-mode provide capfs and use corfu/company-mode as the completion framework. Corfu/company-mode use `insertText` or `label` (using which one is controlled by LSP clients) as candidates' content when showing the popup. 

When an item is selected, corfu/company-mode will replace some content before cursor and insert `insertText` or `label`, then they invoke `:exit-function` provided by eglot/lsp-mode, in which it will delete what has been inserted (aka `insertText` or `label`), call `insert` to insert `newText` or `yas-expand-snippet` to expand `newText` and then insert the result to the document. If `insertText` or `label` is long, people may notice some kind of flicker when inserting and then deleting it(and this exactly is what I want to improve).

Overall, there are two delete/insert operations. The first is deleting part the text users have just inputted and inserting `insertText` or `label`, then the second detele/insert happens, deleting `insertText` or `label` and insert `newText`.
   
# The proposal
The proposal wants to reduce one delete and one insert. Specifically, it wants to reduce the insert in the first delete/insert operation and the delete in the second delete/insert.

## How to archive the goal
Following description focuses on LSP.

I propose to add an `:input-function` property to `completion-extra-properties`. When inserting a candidate, corfu/company-mode first check whether `:input-function` exists, if so, they call it instead of inserting candidate's text(`insertText` or `label` here). 

In `:input-function`, generally capf can check whether `textEdit` exists, apply it to the document. The whole logic of `:input-function` is very similar to what `:exit-function` does ATM.

In this way, `:exit-function` is not needed anymore, and no need to perform twice delete/insert operations.
    
# Final words
I know this proposal refers to not only corfu, and I post it here because I find corfu's code is clean and easy to modify. Actually, I've adviced `corfu--insert` and tested it with my own LSP client lspce. In my experiment, this change really improved completion experience(I should say it's just my subjective feeling).
    
    
Thanks you for reading this. I'd appreciate any feedback.

**Comment by minad** [comment]
Hi @zbelial,

thanks for writing down this proposal, with the goal of improving the completion experience! It is appreciated. But let me be direct right away - I don't think the proposal is beneficial. If an objective improvement can be demonstrated, I may reconsider, but new completion metadata additions involve a lot of coordination between Emacs upstream, Corfu, Company and completion packages. 

Let me elaborate:

1. The already existing `:exit-function` is more general than the proposed `:input-function`. If you enter the text for completion almost completely by hand or by TAB prefix completion, we cannot do anything else than what the `:exit-function` is already doing. We must delete since the text has already been inserted.

2. The flicker you observed is a bug in either the completion UI or the Capf. For example if I use my [Tempel](https://github.com/minad/tempel) template expansion package together with Corfu, there is no flicker, even when inserting large templates. Flicker is not the result of inserting or deleting but of implicit redisplay or an explicit `(redisplay)` call. If you are interested, you should try to debug this. What is causing the unwanted redisplay? Can we optimize this such that the `:exit-function` behaves better? I know that for some time Corfu caused flicker issues since the child frame hiding operation is slow. But now the child frame hiding in Corfu happens via a timer in a deferred fashion and should not cause a delay anymore (See https://github.com/minad/corfu/commit/7d9604d52e2f76c181f5091fd8eae9d5b74124ff and #48).

3. The proposed `:insert-function` seems to mainly about optimizing away an unwanted insert and delete operation. But insert and delete are the bread and butter operations of Emacs buffer manipulations. They are very fast and do not necessarily cause redisplay. As such they are not worth being optimized away. Note that we are also talking about a single insert and delete, not something which happens N times.

4. You wrote that you modified `corfu--insert` to run the `:insert-function`, which is not correct. When `corfu--insert` is called, Corfu is still active. You must make sure that the Corfu completion session is terminated when the `:insert-function` is executed. This is the difference between `corfu--insert` and `corfu--done`, which calls the `:exit-function`.

Please let me know if my answer is helpful. Let's also summon the Lsp-mode maintainer @yyoncho for their opinion.

**Comment by zbelial** [comment]
Hi @minad , thanks for your detailed reply. 

> 
> Let me elaborate:
> 
> 1. The already existing `:exit-function` is more general than the proposed `:input-function`. If you enter the text for completion almost completely by hand or by TAB prefix completion, we cannot do anything else than what the `:exit-function` is already doing. We must delete since the text has already been inserted.
I understand that some deletion is necessary.  I just thought one deletion is not needed for LSP completion. 

> 2. The flicker you observed is a bug in either the completion UI or the Capf. For example if I use my [Tempel](https://github.com/minad/tempel) template expansion package together with Corfu, there is no flicker, even when inserting large templates. Flicker is not the result of inserting or deleting but of implicit redisplay or an explicit `(redisplay)` call. If you are interested, you should try to debug this. What is causing the unwanted redisplay? Can we optimize this such that the `:exit-function` behaves better? I know that for some time Corfu caused flicker issues since the child frame hiding operation is slow. But now the child frame hiding in Corfu happens via a timer in a deferred fashion and should not cause a delay anymore (See [7d9604d](https://github.com/minad/corfu/commit/7d9604d52e2f76c181f5091fd8eae9d5b74124ff) and [Laggy tab and return completion insertion #48](https://github.com/minad/corfu/issues/48)).

I should give more details about what the flicker  in my first post means.  I'll use an example to describe it .
Suppose I have inputted `foo.bar` in a buffer, then the completion popup shows and I select a candidate with content `barbar(param1 type1, param2 type2)  type3`, and the expected string to be inserted in the buffer is `barbar(param1, param2)`. When I press Enter to insert this candidate, these things happen:
1. `bar` in `foo.bar` is deleted
2. then `barbar(param1 type1, param2 type2)  type3` is inserted
3. `:exit-function` is invoked, where `barbar(param1 type1, param2 type2)  type3` is deleted and `barbar(param1, param2)` 

When I said fliker,  I meant that I observed `barbar(param1 type1, param2 type2)  type3` is inserted and then is deleted, and something is inserted again. The text after `foo.` is changed back and forth. 

But this kind of flicker happened not frequently. 

> 3. The proposed `:insert-function` seems to mainly about optimizing away an unwanted insert and delete operation. But insert and delete are the bread and butter operations of Emacs buffer manipulations. They are very fast and do not necessarily cause redisplay. As such they are not worth being optimized away. Note that we are also talking about a single insert and delete, not something which happens N times.

Yes, what I want to eliminate is the insertion in step 2 and deletion in step 3 above. 

> 4. You wrote that you modified `corfu--insert` to run the `:insert-function`, which is not correct. When `corfu--insert` is called, Corfu is still active. You must make sure that the Corfu completion session is terminated when the `:insert-function` is executed. This is the difference between `corfu--insert` and `corfu--done`, which calls the `:exit-function`.
> 
> Please let me know if my answer is helpful. Let's also summon the Lsp-mode maintainer @yyoncho for their opinion.

I'm afraid I don't understand your 4 at all, since I don't have enough knowledge about corfu (and capf). So if I want to introduce `:input-function`, which part of corfu I should modify?

**Comment by minad** [comment]
@zbelial 

> When I said fliker, I meant that I observed barbar(param1 type1, param2 type2)  type3 is inserted and then is deleted, and something is inserted again. The text after foo. is changed back and forth.

Yes, but as I argued, the insertion and deletion is not a problem. See my point (2) above. We have to make sure that no redisplay happens to avoid flicker. The `:exit-function` itself is not the problem. See also my point (1).

**Comment by zbelial** [comment]
> Yes, but as I argued, the insertion and deletion is not a problem. See my point (2) above. We have to make sure that no redisplay happens to avoid flicker. The `:exit-function` itself is not the problem. See also my point (1).

I see. As I said, this flicker doesn't happen all the time, I'll investigate this problem more.  Thanks again.
