### ISSUE TITLE
disable orderless for corfu

### ISSUE THREAD

**Issue by p00f** [minad/corfu#294]
How do I disable orderless for corfu (and only use it for the minibuffer)?

I tried the orderless-fast completion style from the readme to make it fast but that needs me to type 4 characters to get orderless

**Comment by minad** [comment]
On 1/31/23 17:42, Chinmay Dalal wrote:
> How do I disable orderless for corfu (and only use it for the minibuffer)?
> 
> I tried the orderless-fast completion style to make it fast but that
> needs me to type 4 characters to get orderless

You can use setq-local to override the completion style in the buffer
where you use Corfu. However this will have bad side effects for
consult-line, which also relies on the in-buffer completion style.
Therefore there is an override below. You could try (untested):

~~~
(setq-default completion-styles '(orderless basic)
              completion-category-defaults nil
              completion-category-overrides nil)
(add-hook 'corfu-mode-hook
  (lambda ()
     (setq-local completion-styles '(basic)
                 completion-category-defaults nil
                 completion-category-overrides
                 '((consult-location (styles . (orderless)))))))
~~~

But generally this is an unsolved problem without a nice solution. I
happily use Orderless for in-buffer completion, which is why I don't try
harder to find a better solution. Also the Emacs completion system
hasn't been designed with UI-specific completion styles in mind.

**Comment by p00f** [comment]
This works, thanks
