### ISSUE TITLE
Smaller font in overlay than the rest of the buffer

### ISSUE THREAD

**Issue by bbatsov** [minad/corfu#304]
I finally got to trying out corfu today, but I ran into this issue:

![image](https://user-images.githubusercontent.com/103882/225353882-6ee8a344-67cf-4151-b7b0-82a9171c4549.png)

As you can see the font in the overlay is tiny for some reason. Probably something to do with me using Emacs on HiDPI screen without Wayland (I'm using Emacs 28 which doesn't support Wayland and X doesn't scale the fonts properly, so I just double their size). Any idea what I can do to address this problem?

**Comment by minad** [comment]
Okay, I think you should set the frame argument of `set-frame-font`. Hopefully this fixes your issue.

**Comment by bbatsov** [comment]
Yep, you're right. Never noticed that function took any optional params. My bad! Thanks!

**Comment by arialdomartini** [comment]
So, the solution is to provide a 3rd parameter to `set-frame-font`, such as in

```elisp
(set-frame-font "Monoid 14" nil t)
```

**Comment by bbatsov** [comment]
Yeah, exactly.

**Comment by jwiegley** [comment]
I'm running into this too, and nothing that I've tried so far is able to set the right size. I've tried setting `set-frame-font` (with third argument `t`) in the `init.el`, on my `window-setup-hook`, and even in the configuration after loading `corfu`. Although it gets a little bigger with that last one, it still doesn't match the size of the rest of the buffer.

And yet, if I do it manually at the `M-:` prompt, then the problem goes away.

I'm on macOS, so I don't have a `.Xresources` file to modify. How can I tell corfu just to match the size of the rest of the active frame?

**Comment by arialdomartini** [comment]
@jwiegley can you please share the relevant part of your config?

**Comment by jwiegley** [comment]
Sure, here is what I’m using (the whole config is at https://github.com/jwiegley/dot-emacs/blob/master/init.org):

(use-package corfu
  :demand t
  :bind (("M-/" . completion-at-point)
         :map corfu-map
         ("C-n"      . corfu-next)
         ("C-p"      . corfu-previous)
         ("<escape>" . corfu-quit)
         ("<return>" . corfu-insert)
         ("M-d"      . corfu-info-documentation)
         ("M-l"      . corfu-info-location)
         ("M-."      . corfu-move-to-minibuffer))
  :custom
  ;; Works with `indent-for-tab-command'. Make sure tab doesn't indent when you
  ;; want to perform completion
  (tab-always-indent 'complete)
  (completion-cycle-threshold nil)      ; Always show candidates in menu

  ;; Only use `corfu' when calling `completion-at-point' or
  ;; `indent-for-tab-command'
  (corfu-auto nil)
  (corfu-auto-prefix 2)
  (corfu-auto-delay 0.25)

  (corfu-min-width 80)
  (corfu-max-width corfu-min-width)     ; Always have the same width
  (corfu-count 14)
  (corfu-scroll-margin 4)
  (corfu-cycle nil)

  ;; `nil' means to ignore `corfu-separator' behavior, that is, use the older
  ;; `corfu-quit-at-boundary' = nil behavior. Set this to separator if using
  ;; `corfu-auto' = `t' workflow (in that case, make sure you also set up
  ;; `corfu-separator' and a keybind for `corfu-insert-separator', which my
  ;; configuration already has pre-prepared). Necessary for manual corfu usage with
  ;; orderless, otherwise first component is ignored, unless `corfu-separator'
  ;; is inserted.
  (corfu-quit-at-boundary nil)
  (corfu-separator ?\s)            ; Use space
  (corfu-quit-no-match 'separator) ; Don't quit if there is `corfu-separator' inserted
  (corfu-preview-current 'insert)  ; Preview first candidate. Insert on input if only one
  (corfu-preselect-first t)        ; Preselect first candidate?

  ;; Other
  (corfu-echo-documentation nil)        ; Already use corfu-popupinfo
  :preface
  (defun corfu-enable-always-in-minibuffer ()
    "Enable Corfu in the minibuffer if Vertico/Mct are not active."
    (unless (or (bound-and-true-p mct--active) ; Useful if I ever use MCT
                (bound-and-true-p vertico--input))
      (setq-local corfu-auto nil)       ; Ensure auto completion is disabled
      (corfu-mode 1)))

  (defun corfu-move-to-minibuffer ()
    (interactive)
    (let (completion-cycle-threshold completion-cycling)
      (apply #'consult-completion-in-region completion-in-region--data)))
  :config
  (global-corfu-mode)

  ;; Enable Corfu more generally for every minibuffer, as long as no other
  ;; completion UI is active. If you use Mct or Vertico as your main
  ;; minibuffer completion UI. From
  ;; https://github.com/minad/corfu#completing-with-corfu-in-the-minibuffer
  (add-hook 'minibuffer-setup-hook #'corfu-enable-always-in-minibuffer 1))

**Comment by minad** [comment]
@jwiegley I pushed a fix which should ensure that the Corfu child frame font always matches the font of the parent frame. Please let me know if this works in your setup.

**Comment by jwiegley** [comment]
@minad Yes, that seems to have fixed it! Thank you!

**Comment by minad** [comment]
Great, thanks!
