### ISSUE TITLE
Does not work with bash-completion

### ISSUE THREAD

**Issue by Stebalien** [minad/corfu#31]
The `bash-completion` package allows one to use bash to generate `completion-at-point` completions for shell buffers. This works just fine with company, consult, and the builtin completion buffer, but is really buggy with corfu.

To reproduce, load the following with `emacs -Q`:

```elisp
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'bash-completion)
(package-install 'corfu)
(bash-completion-setup)
(shell)
(corfu-mode)
```

Then try to complete a command.

* Completing `pacman -` will show multiple options, including `D`, etc. Subsequently hitting `D` will spit out `No match`. Hitting backspace will now show `--database` (and _always_ `--database`). `--database` is the _last_ option on the list the first time around.
* Completing `man --`, then typing `a` will show `--global-apropose`, ignoring options like `--all` (which is the first one on the list when completing `man --a`.

**Comment by minad** [comment]
Okay, I tried this and it is indeed broken. The problem is that `bash-completion--completion-table-with-cache` returns the original list of candidates, which is then subsequently modified in-place by Corfu. The completion table specification is not 100% precise in this case, but the `complete-with-action/all-completions` function always returns a (filtered) copy of the list. Furthermore the minibuffer.el `minibuffer-completion-help` also mutates the returned list. Therefore this is a bug in `bash-completion`. Fortunately the fix is easy: https://github.com/szermatt/emacs-bash-completion/pull/48

**Comment by Stebalien** [comment]
Ah, thanks for debugging this!
