### ISSUE TITLE
Corfu calls the dynamic completion function many times

### ISSUE THREAD

**Issue by andreyorst** [minad/corfu#317]
Hi. I wanted to point out that I noticed that Corfu calls the completion function a lot of times, much more than `company-mode` or plain `completion-at-point`.  Maybe this is intentional, but it has some implications so I think it worth looking

Here's a minimal example to illustrate what I mean:

```emacs-lisp
(defvar x 0)

(defun delayed (sym) 
  (setq x (1+ x))  
  (message "called %s times" x) 
  '("foobar" "foobaz"))

(defun test-completions ()
  (interactive)
  (when-let ((bounds (bounds-of-thing-at-point 'symbol)))
    (list (car bounds)
          (cdr bounds)
          (completion-table-dynamic #'delayed))))

(add-hook 'completion-at-point-functions 'test-completions nil t)
```

Evaluating this code and putting a point after text `foo` in a `fundamental-mode` buffer with Corfu enabled prints this in the `*Messages*` buffer:

```
called 1 times
called 2 times
called 3 times
called 4 times
called 5 times
```

By comparison, calling `completion-at-point` without Corfu only calls the function two times (one for each `completion-style` perhaps?):

```
called 1 times
called 2 times
```

And with `company-mode` the function is called only once:

```
called 1 times
```

### Why this is important to me

I'm making a minor mode for integration with a language process that provides a basic REPL that can give back completions via a special command.  This means that with Corfu I'm sending five simultaneous requests for completion and in my case, the requests are synchronous because there's no asynchronous CAPF mechanism as far as I know. The manual [suggests](https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html#index-completion_002dat_002dpoint_002dfunctions) using the mentioned `completion-table-dynamic` function and I thought that it will help me defer the synchronous call, but as it seems Emacs still calls this function many times. The reasoning in the manual suggests that the `completion-table-dynamic` may be called fewer times than the `completion-at-point-functions` hook:

> Emacs may internally call functions in completion-at-point-functions many times, but care about the value of collection for only some of these calls. By supplying a function for collection, Emacs can defer generating completions until necessary. 

Because of these repeated calls, the client basically issues 5 blocking requests for completion, and if the REPL process is busy and can't respond immediately (it is single-threaded) the Emacs is blocked until either the request timeout is reached in the client or the client becomes able to process the request.

For now, I've migrated the issue by using the `completion-table-with-cache` function instead of `completion-table-dynamic`, though I'm not sure if it will work robust enough in my case.

**Comment by minad** [comment]
Corfu calls the completion table as much as necessary, but not more. Generally completion tables must be efficient and should use some internal caching. I recommend that you avoid completion-table-dynamic and completion-table-with-cache since these functions are sometimes not ideal. At least make sure that you understand their implementation and the direct implementation of completion tables without helpers. Furthermore I suggest that you checkout my Cape package, which provides some efficient Capfs.

**Comment by minad** [comment]
Also note that as soon as Corfu is active, it calls the completion table on every keypress since the completion table may produce new candidates for the new input. This means there is no alternative to a fast completion table anyway. Corfu at least makes sure that the completion table computation is interrupted when new input is arriving in the meantime.

**Comment by andreyorst** [comment]
> Corfu calls the completion table as much as necessary, but not more.

Can you give more light on why Corfu calls the completion table 5 times while without Corfu it is called only twice?

E.g. without Corfu, calling completion on `math.` and logging from the completion function shows me that it is called with `math` first and then with `math.` second. With Corfu, it is `math`, `math`, `math.`, `math`, `math.`.

**Comment by minad** [comment]
You can print the stack traces and check where the calls are coming from.

**Comment by andreyorst** [comment]
> Checkout the source of completion-table-dynamic. Also note that completion-table-dynamic will only work with the basic completion style.

I've made my own version of `completion-table-with-cache` because we do need to be able to call it on a pretty specific string, as the backend doesn't support any fancy completions, as of today, so the basic style should be fine.

> I recommend that you avoid it.

I'll look into CAPE, but I don't know if in my situation there are better ways. If the process is busy with other tasks it will not even accept the completion request, so my completion function bails out if the process is not ready to accept the input, but because the function is called several times, it bailed out 4 out of 5 calls, because the first completion was still processed.

**Comment by minad** [comment]
> I've made my own version of completion-table-with-cache because we do need to be able to call it on a pretty specific string, as the backend doesn't support any fancy completions, as of today, so the basic style should be fine.

It is the correct thing to write your own completion table with a cache.

I checked your recipe with manual completion and Corfu. I have to correct myself - `completion-table-dynamic` filters out boundaries and metadata. These action cals are are at least not a problem.

When I type `foo TAB`, I get three calls to the completion table with Corfu. The first call tries to complete the existing string (1. `try-complete`). The result is the string `fooba`. Then Cofu checks if completion has finished or if further completion is possible (2. `test-completion`). Since further completion is possible Corfu computes all candidates (3. `all-completions`). I get the same three calls with default completion.
