### ISSUE TITLE
How to auto-confirm minibuffer completion?

### ISSUE THREAD

**Issue by salutis** [minad/corfu#318]
I am testing Corfu in the minibuffer again.  I worked around #245, but I still have one more problem, namely that after Corfu inserts a selected candidate into the minibuffer, I have to press `RET` (again) confirm it.  For example, to switch to the most recently visidet buffer, I have to type `C-x b RET RET` instead of `C-x RET`.  What would be the best way to hook into Corfu/Emacs to automatically confirm the candidate, when completing in the minibuffer?

My configuration:

```elisp
(defun corfu-minibuffer-setup+ ()
  (setq-local corfu-quit-no-match nil
              corfu-quit-at-boundary nil)
  (corfu-mode 1)
  (minibuffer-complete))

(defun corfu-after-change-functions+ (&rest _)
  (when (and (minibufferp)
             (string-empty-p (minibuffer-contents-no-properties)))
    (minibuffer-complete)))

;; NOTE Bring 'minibuffer-default' to front.
(setopt corfu-sort-override-function
        (lambda (candidates)
          (let ((sorted-candidates (funcall corfu-sort-function candidates)))
            ;; 
            (if minibuffer-default
                (cons minibuffer-default
                      (remove minibuffer-default
                              sorted-candidates))
              sorted-candidates))))

(add-hook 'minibuffer-setup-hook #'corfu-minibuffer-setup+)
(add-hook 'after-change-functions #'corfu-after-change-functions+)
```

**Comment by minad** [comment]
> In short, on minibuffer-setup-hook, I set corfu-quit-* to nil, enable corfu-mode, and call minibuffer-complete. Then, on after-change-functions, if the minibuffer is empty, I call minibuffer-complete to make the completion frame re-appear.

Oh, this looks really bad in contrast to https://github.com/minad/corfu#completing-in-the-minibuffer.

> Why not recommended? :)

Because of all the hacks needed. Corfu hasn't been designed for that, but I am glad it works. Nevertheless I prefer to use the most powerful system for each of the separate scenarios. Vertico is more powerful for `completing-read`. :shrug: 

> (At this point, I track one last problem: When I type out the entire candidate manually and press RET, then corfu-history will not have that candidate as the first element.)

Yes, you can probably add this manually somehow to `corfu-history`. But ideally you wouldn't use the separate `corfu-history` for Corfu if `minibuffer-completion-table` is non-nil in the minibuffer and if there is a `minibuffer-history-variable`. You have to adjust consult-history.el somehow to do that.

> Fantastic! It works perfectly:

This does not seem to be entirely correct to me. You still have to distinguish two scenarios somewhat, even if you want to treat them equally:

1. `read-from-minibuffer`: Step-wise completion of input, e.g., `M-:`. There you don't want to return right away.
2. `completing-read`: There exists a `minibuffer-completion-table`, e.g., `C-x b`.
