### ISSUE TITLE
Allow sorting results using corfu-sort-function on top of display-sort-function

### ISSUE THREAD

**Issue by manzaltu** [minad/corfu#332]
In today's implementation, `corfu` will not call `corfu-sort-function` if the completion metadata contains the `display-sort-function` property.
This is, however, unfortunate, since sometimes sorting is wanted on top of the provided `display-sort-function`.
For example, `corfu-history` won't be usable when completing results from lsp-mode, as the latter provides its own `display-sort-function`. Another example would be `corfu-prescient`, which has the same issue with `lsp-mode`, though it does provide the option to enforce sorting using `corfu-prescient-override-sorting`, however, this is unwanted as it completely overrides the LSP provided one.
In these examples, `lsp-mode` sorts results based on context (e.g. local variables first, then global ones). There is no reason that an additional recency based sorting would need to be mutually exclusive with the contextual one.

In order to support this scenario, I created my own sorting function, and set it in `corfu-sort-override-function`. It uses `corfu-sort-function` to sort results that got processed by `display-sort-function`:

```el
(setq corfu-sort-override-function
  (lambda (candidates)
    (let ((candidates
           (let ((display-sort-func (corfu--metadata-get 'display-sort-function)))
             (if display-sort-func
                 (funcall display-sort-func candidates)
               candidates))))
      (if corfu-sort-function
          (funcall corfu-sort-function candidates)
        candidates))))
```

While it works, I'm not a big fan of this solution, as I had to use the internal `corfu` function `corfu--metadata-get` that can get changed in future versions. I also had to use `corfu-sort-override-function` that might be needed in other completion scenarios. If we could add this capability directly to corfu, it will make more sense, IMO.

**Comment by minad** [comment]
Thanks for the proposal! Iirc this has already been discussed at some point on the issue tracker - maybe on the Vertico tracker, which has a similar design.

I don't want to add an additional sort function or change the semantics of `corfu-sort-function`. We already have `corfu-sort-override-function` which is meant for scenarios exactly like yours and other special fine tuning. 

The `corfu-sort-function` is supposed to only set-in if the completion backend itself does not pre-sort the candidates. Most of the completion UIs work like this. It is important that sorting functions specified by completion backends are respected. The assumption is that if a backend specifies a sort function, it also wants to control the candidate order. For example `cape-history` wants to retain the order of the candidates which reflects the history. Lsp-mode provides its own sorting function, since the idea is that the lsp server "knows" the best ordering. 

It seems you are not perfectly happy with the choice being made by Lsp-mode, which is of course understandable if the candidates provided by the server are not ordered meaningfully. Maybe this can be improved in Lsp-mode, or maybe not. That's why we have the `corfu-sort-override-function`.

I think it is a rather elegant and simple design. I don't see anything wrong to take your function and add it to a personal library (or the Corfu wiki) and use it as follows (I use a `+corfu` pattern for personal package addons btw).

~~~ elisp
(defun +corfu-combined-sort (candidates)
  (let ((candidates
         (let ((display-sort-func (corfu--metadata-get 'display-sort-function)))
           (if display-sort-func
               (funcall display-sort-func candidates)
             candidates))))
    (if corfu-sort-function
        (funcall corfu-sort-function candidates)
      candidates)))

(setq corfu-sort-function #'+corfu-combined-sort)
~~~

The alternative would be to hard code the functionality either in `corfu--sort-function` (which can be advised) or in the candidate computation (which is already complex enough).

https://github.com/minad/corfu/blob/1f2ffa03b3cd2fbb6e398c8b3cb8b0daae53f7d4/corfu.el#L569-L573

https://github.com/minad/corfu/blob/1f2ffa03b3cd2fbb6e398c8b3cb8b0daae53f7d4/corfu.el#L575-L613

Also note that in addition to this existing complexity, completion styles also have the ability to override the sort function via metadata adjustment. For example the `flex` completion style uses this mechanism.

**Comment by manzaltu** [comment]
Thank you for your response. I took your advice and added the combined sort example to the corfu wiki.
