### ISSUE TITLE
Completion style doesn't apply when using `cape-wrap-buster` with eglot

### ISSUE THREAD

**Issue by pushqrdx** [minad/corfu#358]
I noticed that fuzzy filtering based on my completion style stops working when I used `cape-wrap-buster` to solve #353, and it seems like I have to choose between one or the other. I have tried the [wiki suggestions](https://github.com/minad/corfu/wiki#filter-list-of-all-possible-completions-with-completion-style-like-orderless) but none of them worked.

**Comment by minad** [comment]
No, that's not entirely correct. The LSP server computes the candidates based on the buffer input (when the cache is busted) and uses its own custom filtering algorithm to do so. But completion style filtering still happens afterwards, e.g., `flex` adds highlighting. For Orderless however `cape-wrap-buster` supports a special mechanism. After a space has been inserted, the candidates won't be requested again from the server, such that you can post filter the candidates with additional Orderless components.

**Comment by minad** [comment]
Note that the phenomenon is not totally uncommon. There are other Capfs with a similar behavior, e.g., `cape-dabbrev` or `cape-dict`. Both compute the initial set of candidates based on the prefix input. 

Take a look at `cape-dict`, which uses `cape--dynamic-table`: 

* https://github.com/minad/cape/blob/758b45d133dd96a1787099af329c917d02635d0d/cape.el#L559

The candidates are computed if the input became invalid, but only if Orderless filtering hasn't been initiated:

* https://github.com/minad/cape/blob/758b45d133dd96a1787099af329c917d02635d0d/cape.el#L255-L256

**Comment by pushqrdx** [comment]
> No, that's not entirely correct.

@minad I am describing what's happening in my setup with `clangd` no matter which completion style I use (flex, orderless, hotfuzz), flex matching doesn't work.

Here's without the `cape-wrap-buster`:
![image](https://github.com/minad/corfu/assets/25884937/bcb11d32-1c21-4a79-9e44-8118e292dcdc)

And here's with:
![image](https://github.com/minad/corfu/assets/25884937/33a5da29-f4ea-4581-95f0-a83dc63176ef)

As you can see once I type the letter `L` the completion popup goes away.

Side note: I find it very clunky having to use space to suspend fetching, let alone getting it to actually work which I never managed to achieve.

**Comment by minad** [comment]
Yes, this is expected. The input `prl` is not understood by the LSP server, since it seems to use either substring or prefix filtering on the server side. Note that the server filtering is not controlled by Emacs.

1. In your first example the candidates are retrieved as soon as you type `p` or `pr`, depending on the value of `corfu-auto-prefix`. The rest of your input `ln` doesn't renew the candidates, but the completion style filtering still takes place.
 
2. In your second example with the cache buster, the candidates are retrieved on every key press from the server, but the server doesn't understand the prefix `prl` and doesn't return anything. Maybe you can configure your server to perform fuzzy filtering instead, which should reduce the mismatch.

> Side note: I find it very clunky having to use space to suspend fetching, ...

The mechanism is owed to the fact that the LSP protocol and some other Capfs choose to filter candidates based on the prefix with their own filtering algorithms out of Emacs' control. Completion styles is the Emacs filtering mechanism and as such is executed on the Elisp side of things. 

For Orderless users, typing SPC feels natural so I don't share your perception that this is clunky. I use Orderless all the time in the minibuffer and like to have it available for normal buffer completion too.

> ...let alone getting it to actually work which I never managed to achieve.
 
Try emacs -Q with `cape-dict` and `orderless`. There you will certainly be able to observe the effect.

**Comment by pushqrdx** [comment]
@minad Well, your explanation makes sense, however, `clangd` in sublime text doesn't behave that way and I am getting expected results even with `prl` as prefix. (It also doesn't suffer from the problem described at #353 where `clangd` doesn't reply with a full list of candidates the first time). So, if it's a server flaw, I don't see why doesn't it also happen in sublime text or vscode with `clangd` lsp? Oh and it doesn't happen in neovim as well.

**Comment by minad** [comment]
That's interesting. This means that the server should return candidates for fuzzy input. I don't know why it doesn't happen. Maybe look at the LSP protocol log to see what is going on?

**Comment by pushqrdx** [comment]
@minad I am not sure how to do that but here's what happens in sublime text for instance, I type `std::prl` and quit out of the auto complete popup, then manually trigger auto complete, I get expected completion from the server as follows

![image](https://github.com/minad/corfu/assets/25884937/6b90fe22-b5eb-4e5e-a31a-bf884b94f5b9)

and here's how it looks like without cancelling auto completion for the first time (not that I get a full list without any missing items like it does in Emacs)

![image](https://github.com/minad/corfu/assets/25884937/41d83326-9a4e-4364-a7f6-59b92d3a37eb)

**Comment by minad** [comment]
I am afraid I cannot help you further. This needs debugging of the LSP Capf and protocol. Debugging such issues or other backend issues is out of scope of Corfu or Cape.

**Comment by minad** [comment]
Maybe @jdtsmith is able to help, since he did a lot of experimentation regarding LSP and the cache busting mechanism. Not sure if he has observed similar issues before, but afaik he mostly uses the Python LSP server.

**Comment by pushqrdx** [comment]
@minad appreciate your help, I'll keep investigating then, will update this thread if I find any workarounds

**Comment by minad** [comment]
Okay, please let me know if you figure something out. I am interesed in having such issues fixed. If everything works as expected up to the return value of the Capf and the candidate filtering, then it could still be that Corfu bails out of completion for some other reason.

The bail out reasons are quite complicated:

1. `corfu--capf-wrapper` checks the validity of the Capf return value, see https://github.com/minad/corfu/blob/5476fc2cccfec1859849d3fab3d6dfef827568cb/corfu.el#L368-L375.
2. `corfu--capf-wrappper` checks if the returned completion candidates are actually valid for nonexclusive Capfs, see https://github.com/minad/corfu/blob/5476fc2cccfec1859849d3fab3d6dfef827568cb/corfu.el#L376-L386.
3. `corfu--continue-p` checks if completion should continue given a new command in the pre-command-hook, see https://github.com/minad/corfu/blob/5476fc2cccfec1859849d3fab3d6dfef827568cb/corfu.el#L758-L786.
4. `corfu--exhibit` has a whole bunch of conditions to check if completion is to be continued after a command, see https://github.com/minad/corfu/blob/5476fc2cccfec1859849d3fab3d6dfef827568cb/corfu.el#L1079-L1101.

**Comment by minad** [comment]
This issue reminded me that I wanted to add some debugging functionality to Cape. I've added that now in https://github.com/minad/cape/commit/f5364cd1455fae83885092a32ab74e90a177c419. Maybe this is helpful to debug issues like this one.

**Comment by pushqrdx** [comment]
@minad @jdtsmith So I stripped down my setup and started to test `corfu` with `lsp-mode` instead of `eglot` and it appears that this problem **doesn't** happen with `lsp-mode`.

First here's my `corfu` configuration:
```elisp
(feature 'corfu
  (:elpaca (corfu cape))
  (:after 'window-setup-complete)
  (:customize
   corfu-auto t
   corfu-auto-prefix 1
   corfu-auto-delay 0.05
   corfu-quit-no-match t
   corfu-quit-at-boundary t
   corfu-preview-current nil
   corfu-echo-documentation nil)
  (:enable :global t))
```

And here're my `eglot` and `lsp-mode` configurations along with gifs to demonstrate what happens with both _(note that both are using `completion-styles '(basic flex)`)_

#### Eglot
```elisp
(feature 'eglot
  (:after 'window-setup-complete)
  (:customize
   eglot-auto-display-help-buffer nil
   eglot-ignored-server-capabilities '(:documentHighlightProvider :inlayHintProvider))
  (with-eval-after-load 'eglot
	(advice-add 'eglot-completion-at-point :around 'cape-wrap-buster)))
```

![eglot](https://github.com/minad/corfu/assets/25884937/3e49a3b7-2280-4364-b844-2db31334197f)

#### LSP Mode
```elisp
(feature 'lsp
  (:elpaca lsp-mode)
  (:after 'window-setup-complete)
  (:customize
   lsp-completion-provider :none
   lsp-enable-folding nil
   lsp-enable-on-type-formatting nil
   lsp-enable-suggest-server-download nil
   lsp-enable-symbol-highlighting nil
   lsp-enable-text-document-color nil
   lsp-headerline-breadcrumb-enable nil)
  (with-eval-after-load 'lsp-mode
	(advice-add 'lsp-completion-at-point :around 'cape-wrap-buster)))
```

![lsp](https://github.com/minad/corfu/assets/25884937/b312cfd1-0729-436e-9cc0-83132458659c)

---

As you can see, both are using `cape-wrap-buster` but for some reason flex matching doesn't work with `eglot`. Another interesting find is that `company` mode works fine without `cape-wrap-buster` with `lsp-mode` **but has the same behavior as `corfu` with `eglot`**

**Comment by minad** [comment]
@pushqrdx Thanks. Please try to narrow down the problem systematically, ideally starting with manual completion as @jdtsmith mentioned. One problem could be that you are using the completion style `(basic flex)`. Only try `(flex)` to be sure.

Throwing lsp-mode into the mix complicates the analysis further. Lsp-mode itself needs specific completion-styles configuration for the colorization as documented in the Corfu wiki. Therefore colorization is missing in your test. The hanging problem and other issues which have already been reported before on the lsp-mode bug tracker. The hanging can be fixed with `cape-capf-noninterruptible`.

Company and Corfu+`corfu-capf-buster` should show the same behavior, since both throw away completion tables on every key press. You should be able to confirm this with `cape-capf-debug`. 

You can compare the behavior and the debug logs of two configurations side by side and check if you spot any differences. `cape-capf-debug` will tell you exactly how the Capf has been called, including the arguments and the return value.

~~~ elisp
(corfu-mode 1)

;; Make sure that we use flex
(setq-local completion-styles '(flex)
            completion-category-overrides nil
            completion-category-defaults nil)

;; Setup the Capf
(setq-local completion-at-point-functions (list (cape-capf-debug (cape-capf-buster (cape-capf-noninterruptible #'eglot-completion-at-point)))))
~~~

~~~ elisp
(company-mode 1)

;; Make sure that we use flex
(setq-local completion-styles '(flex)
            completion-category-overrides nil
            completion-category-defaults nil)

;; Setup the Capf
(setq-local completion-at-point-functions (list (cape-capf-debug #'eglot-completion-at-point)))
~~~

**Comment by pushqrdx** [comment]
@minad Alright thanks to your suggestions both the hanging and highlighting problems with `corfu` + `lsp-mode` are fixed, and I was able to confirm that the problem with fuzzy matching occurs only with `eglot` for both `company` and `corfu`. I also tested both `corfu` and `company` with `lspce-mode` to make sure that the problem only happens with `eglot` which is true.

I am not sure why this is happening only with `eglot` to be honest but it doesn't seem to be related to the completion frontend.

---

Side Note: I have also noticed some weird behavior that I can't explain but will leave here for future reference, sometimes #353 behaves in a different way without using `cape-wrap-buster` where the first completion list is incomplete but after typing a few more letters a new completion list is requested with the correct items. I am not sure what triggers the refresh of the candidate list if `cape` is not involved but I can't always reproduce it, so I am going to leave it at that.

**Comment by pushqrdx** [comment]
One other question, what if I want to disable any highlighting in the completion popup? If I don't set `completion-category-*` the first character is still highlighted

**Comment by jdtsmith** [comment]
eglot hard-codes the completion style to `(flex basic)`  I do this in an `eglot-managed-mode-hook` function to override the override:

```elisp
    (setf (alist-get 'styles
 		     (alist-get 'eglot completion-category-defaults))
 	  '(orderless))
```

**Comment by minad** [comment]
@pushqrdx Thanks.

> ...and I was able to confirm that the problem with fuzzy matching occurs only with eglot for both company and corfu. I also tested both corfu and company with lspce-mode to make sure that the problem only happens with eglot which is true.

If you want report this issue on the Eglot issue tracker with a well-prepared reproducible example, but better mention only Company, since the Eglot author doesn't officially support Corfu.

> I am not sure why this is happening only with eglot to be honest but it doesn't seem to be related to the completion frontend.

Yes, it is unlikely that the issue is directly caused by the frontend.

> I am not sure how to prevent lsp-mode from setting the buffer local completion-category-defaults...

You have to correct the completion style settings manually after enabling lsp-mode. I've asked the lsp-mode maintainers before to support Corfu via the `lsp-completion-provider`.  If you are interested you could ask again on the tracker. Someone should try to provide a patch which sets up a working configuration for `lsp-completion-provider=corfu`. (The name should probably be changed to `lsp-completion-frontend`.)

> One other question, what if I want to disable any highlighting in the completion popup? If I don't set completion-category-* the first character is still highlighted.

You can implement a custom completion style, which doesn't add highlighting. You could base the style on `flex` and drop the faces from the results.

> As you can see company has proper highlighting + correct order println is first item after filtering, while corfu also has correct highlighting but is partial_ordering as the first item in the list (even though the shorter match should take precedence)

I don't know why this happens. I cannot reproduce the problem in a controlled test environment starting from emacs -Q with the following test capfs (for neither `test-capf1` nor `test-capf2`):

~~~ elisp
(defun test-capf1 ()
  (pcase (bounds-of-thing-at-point 'word)
    (`(,beg . ,end)
     `(,beg ,end ("partial_ordering" "println")))))

(defun test-capf2 ()
  (pcase (bounds-of-thing-at-point 'word)
    (`(,beg . ,end)
     `(,beg ,end
       ,(lambda (str pred action)
          (if (eq action 'metadata)
              '((display-sort-function . identity)
                (cycle-sort-function . identity))
            (complete-with-action action '("partial_ordering" "println") str pred)))))))

(setq-local completion-at-point-functions (list #'test-capf2)
            completion-styles '(flex)
            completion-category-overrides nil
            completion-category-defaults nil
            corfu-auto-prefix 1
            corfu-auto t)

(package-initialize)
(corfu-mode 1)

;; Type prln
~~~

**Comment by pushqrdx** [comment]
@minad it appears to be happening because of `flex` I think it's reordering items and for some reason favoring `partial_ordering` over `println` for the input, I was wondering why this doesn't happen with company mode as I initially thought it's using my completion style as well, but I changed my completion style to just `basic` and company seems to still do fuzzy matching, so am I correct in assuming that company mode does not use `completion-styles` and has some built-in flex/fuzzy matcher?

**Comment by minad** [comment]
@pushqrdx Yes, `flex` reorders the candidates. But in my test above `println` is prioritized higher than `partial_ordering`, since the distance to the input is shorter. I don't see your issue with my test Capfs. `company-capf` also relies on the `completion-styles`, similar to Corfu. lsp-mode effectively disables the completion styles, since it installs its own `lsp-passthrough` style.

**Comment by pushqrdx** [comment]
@minad then this whole thing is started to make my head spin, I am only using `company-capf` as my company backend, and for some reason, and even though my `completion-category-*` is set to nil as well as `completion-styles` to basic, company is still performing fuzzy matching with lsp mode only in C++ buffers. in elisp buffers it's following my basic completion style correctly and not performing any fuzzy matching.

Also if flex is ordering `println` first based on distance in your tests, why doesn't it do that with `lsp-mode` in my case, I have made extra sure that everything is set correctly and am doing all of this on a fresh emacs setup without any other plugins that might be interfering or setting up things on their own.

**Comment by pushqrdx** [comment]
Alright I think I figured out why flex orders `println` second, It's also taking into account the function signature...
