### ISSUE TITLE
Trigger eldoc when going through candidates

### ISSUE THREAD

**Issue by johannesneyer** [minad/corfu#36]
I'd like to make corfu trigger eldoc when going through candidates.

I tried `(eldoc-add-command 'corfu-next)` but it didn't work.

This is what I tried:

```elisp
(use-package corfu
  :bind (:map corfu-map
         ("TAB" . corfu-next)
         ([tab] . corfu-next)
         ("S-TAB" . corfu-previous)
         ([backtab] . corfu-previous))
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-auto-prefix 1)
  (corfu-quit-at-boundary t)
  (corfu-quit-no-match t)
  :init
  (corfu-global-mode))

(use-package eldoc :defer
  :custom
  (eldoc-idle-delay 0.1)
  :config
  (eldoc-add-command 'corfu-next))
```

Any ideas?

**Comment by minad** [comment]
You would have to tell the currently selected corfu candidate to eldoc. However it would probably be better to approach this differently, the completion backend provides annotations and signatures. These could be fed directly into eldoc.

**Comment by minad** [comment]
You can try this:

~~~ elisp
(advice-add #'corfu--goto :after #'corfu--show-docsig)

(defun corfu--show-docsig (_index)
  (let ((message-log-max nil))
    (if-let (fun (and (>= corfu--index 0)
                      (plist-get corfu--extra-properties :company-docsig)))
        (message "%s" (funcall fun (nth corfu--index corfu--candidates)))
      (message ""))))
~~~

**Comment by jdtsmith** [comment]
I wonder if you'd be interested to support `:company-docsig` in `corfu`?  I know many CAPF backends implement it.  This extra attribute maps to the `'meta` command of company, which simply echoes a string to the echo buffer when a new selection is made.  In many ways this provides "eldoc while completing", which may in fact be what @johannesneyer is after.

**Comment by minad** [comment]
@jdtsmith Yes, the snippet above implements this. I may add support. But in general I am not a fan of the company extensions. The proper way to do this would be to propose and add more *standard* keys to `completion-extra-properties`, which provide the metadata. This process is a bit tedious however and I am already busy with some modifications to the `completing-read` API.

**Comment by jdtsmith** [comment]
Thanks, I see that now.  Sorry, I hadn't looked closely at your code.  

Yes, the package-specific standards creep is a bit unfortunate, but no doubt it spurred much of the completion improvement in recent years.  It's interesting that most modes have gravitated away from company-specific backends once company-capf landed.  One approach would be to support `:company-docsig` now as a "placeholder" for a future similar, Emacs-official extra property keyword, then obsolete it down the road.   I was able to get pretty good `company-kind` approximation using the new `affixation-function`: 

![image](https://user-images.githubusercontent.com/93749/126051107-20d160d0-a7c5-40a9-aacc-8d19a105449c.png)

**Comment by jdtsmith** [comment]
The doc echo works great.  Many modes style their docsig messages in advance; perhaps a test could be added to `corfu--echo` to add the face only if no face info is already set on the docsig?  I think I've seen that trick used elsewhere among your tools.  Thanks for implementing.

**Comment by minad** [comment]
> Many modes style their docsig messages in advance; perhaps a test could be added to corfu--echo to add the face only if no face info is already set on the docsig? 

That's a good idea. I could also remove the corfu-echo face altogether. What is company doing? Does it add extra styling? I added corfu-echo since I wanted to fade out the echo message a little bit.

**Comment by jdtsmith** [comment]
I don't know about company, but an iPython mode I'm working on inherits the iPython styling from the process itself, and then adds the "blurb" in front with `'font-lock-doc-face`.  It looks like this:

![image](https://user-images.githubusercontent.com/93749/126655678-4cd4b926-40c9-4e04-b2d7-8ca4db3fc95d.png)

I found this code in consult (using consult+embark+multi-occur ;):

```elisp
                     (if (text-property-not-all 0 (length ann) 'face nil ann)
                          ann
                        (propertize ann 'face 'completions-annotations))))))
```

**Comment by minad** [comment]
See https://github.com/minad/corfu/commit/71cedfba75dbf7282898964fe435883930d06ada

**Comment by jdtsmith** [comment]
Looks great. But company is _way faster_ than corfu pulling and displaying docsig info.  It's not a delay on the backend, because I actually cache the results during one completion.   I think it's because company does not use an idle-timer, but instead just updates the docsig instantly each time a new selection is made.  This works very well in practice.  Often sometimes docsig info is available "in stream" with completion data anyway, so it's no additional lookup penalty. 

Eldoc is a different matter; there you want to wait a bit to see if the point has settled before bothering.  In practice I use the same function for both eldoc and docsig.

**Comment by minad** [comment]
> Looks great. But company is way faster than corfu pulling and displaying docsig info.

This is intentional, please take a look at the code. You can set `corfu-echo-documentation=t`.

**Comment by jdtsmith** [comment]
Sorry I missed that; identically performant with this setting enabled!  After your comment, I experimented with a bit of delay as well to save a bunch of calls to the backend when scrolling through, and 0.25s works well for me.

BTW, can child frames have multiple windows in them? Might be cool to show doc-buffer info in a borderless window adjacent to the candidates. Jedi and many others (CIDER I think) use tooltips for this:
![](https://aliquote.org/img/20130211201329.png)
M-h is also pretty easy (though I'd prefer M-? since M-h means "mark this paragraph" in my mind).

**Comment by minad** [comment]
I guess one could use tooltips for this, but this seems like an abuse. The correct way is to use an additional child frame. However this is functionality I would definitely not want to have in Corfu itself. It should go into an extension package (like the extension packages I have in Vertico). Corfu should then be slightly restructured internally such that the child frame/popup code could be shared at least for the main Corfu popup and for such auxiliary popups. Personally I am not overly interested in this functionality, I see Corfu more as a tool for quick and non-obtrusive completion and not so much for exploration. But if you are interested in implementing this - it would be great to have this feature as an extension.

**Comment by minad** [comment]
Maybe it also makes sense to degrade the `corfu-show-documentation` and `corfu-show-location` commands to an extension. Then the user could either install an extension providing these two commands or an extension providing the popup help.

**Comment by jdtsmith** [comment]
RE extensions: either way seems fine.  Perhaps a good way to evaluate it is if most people will want the extensions, they should have perhaps been left in the core.  I suspect that would be true for the extensions thus far, given one of your larger target audiences will be former company users.  On the other hand, if you offload all `:company-blah`-dependent features to an extension like `corfu-company-compat` [1], you can jettison(/deprecate) it once the right emacs-equivalent metadata materializes, and replace it with an equivalent package targeting the shiny new emacs features.  You could use its README to opine on why non-standardized, tool-specific APIs like that are non-ideal.  It would also make a nice small target for discussion with emacs devels (goal: replace this with inbuilt, superior, standardized functionality).  I think I talked myself into it ;). 

RE tooltips: seems that you could "extend" the corfu frame with a child frame of its own, and place doc information there.  I'm actually on the fence about whether I'd even use such a thing, so I doubt I'd spend the time working on it; more technical curiosity if there was a way to gang child frames (and quit abusing tooltips!).

[1] I certainly want to see icon or rich category (prefix?) 'kind' support, so that sounds like it could fit in such an extension (but more likely an "affiliated package" given your outlook on that).

**Comment by minad** [comment]
> RE extensions: either way seems fine. Perhaps a good way to evaluate it is if most people will want the extensions, they should have perhaps been left in the core.

Yes, that's a reasonable approach.

> On the other hand, if you offload all :company-blah-dependent features to an extension like corfu-company-compat [1], you can jettison(/deprecate) it once the right emacs-equivalent metadata materializes, and replace it with an equivalent package targeting the shiny new emacs features. 

I assume that most of the company extensions are somehow reasonable, so if they get substituted by Emacs equivalents we can simply replace this part of the code, e.g., it could be as easy as `:company-docsig -> :docsig`.

> RE tooltips: seems that you could "extend" the corfu frame with a child frame of its own, and place doc information there.

I don't understand what you mean here.

**Comment by jdtsmith** [comment]
> > RE tooltips: seems that you could "extend" the corfu frame with a child frame of its own, and place doc information there.
> 
> I don't understand what you mean here.

Just musing on how you'd arrange another doc-holding child frame to cooperate with the normal corfu child-frame (I learned that child frames can have their own child frames).
