### ISSUE TITLE
corfu-complete-partially

### ISSUE THREAD

**Issue by mpedramfar** [minad/corfu#363]
Hi and thanks for the great package!

Is there a way to tell corfu to partially complete instead of inserting a full item?
What I mean is this:
When I write `(corf` in an elisp buffer and press TAB once, it shows the list of all completions and all of them contain `corfu-` (most of them start with it, but some, like `global-corfu-mode` contain it). If I press TAB again, it inserts the first match. What I'd like it to do is to change `(corf` into `(corfu-` and keep the completion window open for further input. 
Somehow similar to the way bash does its completions.

I looked through the README and skimmed some of previous issues and couldn't find out how this could be done. The only mention of partial completion was about `completion-styles` and setting `(setq completion-styles '(partial-completion))` didn't do what I'm looking for.

**Comment by mpedramfar** [comment]
Actually, it might be better if the partial completion is only done among currently visible candidates.
So if in the previous example, there is a function named `corfz-something` but it is not currently visible among the candidates I'm seeing, and all the candidates I'm seeing contain `corfu-` in them, I would still like TAB to complete `(corf` to `(corfu-`.

**Comment by minad** [comment]
Hi! If you set corfu-preselect=prompt the first candidate is not selected automatically. Then TAB bound to corfu-complete should complete your input step wise, instead of inserting a selected candidate. For this to work you need a completion style like basic, substring or maybe partial-completion. The completion style will use all available candidates and not only the visible ones. The behavior is the same as minibuffer completion with the default completion UI (without vertico, ivy, etc).

**Comment by mpedramfar** [comment]
Thanks!
