### ISSUE TITLE
(Rust) Really slow autocomplete

### ISSUE THREAD

**Issue by jfaz1** [minad/corfu#364]
Hello,

I *really* like Corfu, but I have a ton of delay when it comes to using autocomplete. I've tried setting the delay to various values like 0, 0.02, 0.2, and it still takes a long time to complete even when there aren't that many completions (e.g. 2-3 seconds). 

Moreover, when accessing methods, the moment I input the `.` it freezes for ~0.5 seconds before displaying the methods in whatever object I'm trying to access.

The reason this issue is strange is because besides having a beefy setup, using `company` has no such issues. Even with a delay of 0 everything is snappy and never freezes. It's my understanding that Corfu is meant to be simpler/faster than company, so I'm sure there's something strange happening. I profiled to try seeing what was happening, but it does seem like an issue with Corfu:

```
        6469  95%  - corfu--all-completions
        6469  95%   - completion-all-completions
        6469  95%    - apply
        6469  95%     + #<subr completion-all-completions>
```

I'm not touching any other settings besides enabling auto completion, and I'm using Eglot/Rustic (default settings on both).

**Comment by minad** [comment]
This is indeed strange since both Company and Corfu go through `completion-all-completions`. The expensive part is the filtering here and it depends on your `completion-styles` setting. Both Company and Corfu should be equally fast. It could also be that you configured additional expensive Capfs which are active in Corfu.

Can you please create a minimal configuration based on emacs -Q and paste it below? The configuration snippet should only configure Corfu and no other packages. This can then give us some clue on what is wrong. Please also take https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-clients into account. I close the issue for now since it is likely a configuration issue.
