### ISSUE TITLE
Ignoring dot files in the eshell completion

### ISSUE THREAD

**Issue by arael** [minad/corfu#365]
Is there any way to filter out the dot files in the eshell completion?

Ideally, I would like them to appear only if I input a dot as the first character.

I have searched in the variables but I could not find anything regarding keywords such as "filter" and "ignore".

Thank you very much for any suggestion.

**Comment by minad** [comment]
No, this is not supported. Vertico has special support which could be added here maybe (see below). But then Eshell completion uses quoting and the file category may not be defined as clearly. That's why I haven't done this so far. I also believe that ignoring should actually be more of a matter of the backend and/or completion style. If you are interested you can conduct experiments along these lines but for now I'd like to keep things as is.

https://github.com/minad/vertico/blob/5780fac84f67c19cd6906077ecd636bac3c0c7ad/vertico.el#L343

**Comment by arael** [comment]
Understandable. Thank you for taking your time to consider my issue.
