### ISSUE TITLE
README for corfu-move-to-buffer may need update

### ISSUE THREAD

**Issue by jeff-phil** [minad/corfu#416]
Looking at README the code section for `corfu-move-to-buffer ()`, I could not seem to get that to work properly.  I needed to change this line:

``` elisp
      (apply #'consult-completion-in-region completion-in-region--data))))
```

Here is the end result that works for me with last line updated:

``` elisp
  (defun corfu-move-to-minibuffer ()
    (interactive)
    (when completion-in-region--data
      (let ((completion-extra-properties (nth 4 completion-in-region--data))
            completion-cycle-threshold completion-cycling)
        (apply #'consult-completion-in-region (seq-take completion-in-region--data 4)))))
```

Is this correct now, and README needs updating?

**Comment by jeff-phil** [comment]
@minad 

I was validating the update, one small change is needed since `completion-extra-properties` is nil after moving completion to minibuffer. I believe `completion-extra-properties` should be set to `(car extras)`:

``` emacs-lisp
(defun corfu-move-to-minibuffer ()
  (interactive)
  (pcase completion-in-region--data
    (`(,beg ,end ,table ,pred . ,extras)
     (let ((completion-extra-properties (car extras))
           completion-cycle-threshold completion-cycling)
       (consult-completion-in-region beg end table pred)))))
(keymap-set corfu-map "M-m" #'corfu-move-to-minibuffer)
(add-to-list 'corfu-continue-commands #'corfu-move-to-minibuffer)
```

**Comment by minad** [comment]
Thanks, you are right. All this code in the README is not great. Maybe I should move all of it to the wiki.

**Comment by jeff-phil** [comment]
I've been pondering this for past couple days.  

On one hand, corfu has some complex recipes due to it's power - and probably few that can spell that out properly (clear, concise and elegant in documentation and code) for others like you do.  For example, your fix is much clearer and maintainable than what I originally sent.  Not sure it matters other than I feel smarter after seeing your solution, and my fix may have likely caused unnecessary long-term bugs, i.e. more work down the road.  🤷‍♂️

Maybe start with one section, put it in wiki and see how turns out or evolves?

And if you ever need more hands, I am always willing to support where I can.  Just holla.

**Comment by minad** [comment]
jeffphil ***@***.***> writes:

> On one hand, corfu has some complex recipes due to it's power - and probably
> few that can spell that out properly (clear, concise and elegant in documentation
> and code) for others like you do. For example, your fix is much clearer and
> maintainable than what I originally sent. Not sure it matters other than I feel
> smarter after seeing your solution, and my fix may have likely caused
> unnecessary long-term bugs, i.e. more work down the road. 🤷‍♂️

The solutions I put in the README should be at least somewhat stable and
robust. However they cannot be part of the package itself because they
address integration or configuration issues, like for example in this
case the Corfu <-> Consult integration.

I could also move all of that code to the wiki, however it also makes
sense to show case some of the particularly neat solutions in the
README, also for educational purposes. I think that's the main reason
that they are there, in contrast to some other wiki code.

> And if you ever need more hands, I am always willing to support where I can.
> Just holla.

Thanks, your bug reports are very helpful. If you come up with special
tweaks, feel free to document them in the wiki. Also proofreading the
wiki, readme, docstrings, the code itself is immensely helpful. I think
this is an area where my packages are lacking, the documentation
(docstrings and manual/readme) could be better, better structure,
clearer explanations and so on.
