### ISSUE TITLE
Can we exclude double-quotes from the cape-emoji prefix?

### ISSUE THREAD

**Issue by LemonBreezes** [minad/corfu#423]
Hi. So currently I have emoji autocompletion in docstrings but `cape-emoji` picks up the double-quotes as part of the prefix, so no completions are returned when writing Elisp documention and have the point before a double-quote. I also see that `cape-emoji` does not return any completions with double-quotes. Can we exclude double-quotes in the prefix regexp?

**Comment by minad** [comment]
I have difficulties reproducing this issue. Please provide a minimal recipe.

`cape-emoij` internally uses `thing-at-point-looking-at`, so the problem lies there. Can you create test cases, where you invoke `thing-at-point-looking-at` with `M-: at point and check if it returns an incorrect result?

Do you use Emacs 30? It seems there has been a recent change to this function which may have introduced a regression, see https://github.com/emacs-mirror/emacs/commit/bc099295dd24d059d3358acf5653ced9c9292e41. In this case we have to check if the upstream change caused the problem and we have to check if the changed behavior is indeed correct. If not, an upstream bug should be submitted. But then I suspect that other packages may also be affected by this problem.

**Comment by LemonBreezes** [comment]
> I have difficulties reproducing this issue on my setup on Emacs 29. Please provide a minimal recipe, Emacs versions and package versions, and the steps needed to reproduce the problem.
> 
> `cape-emoij` internally uses `thing-at-point-looking-at`, so the problem lies there. Can you create test cases, where you invoke `thing-at-point-looking-at` with M-: at point and check if it returns an incorrect result?
> 
> Do you use Emacs 30? There has been a recent change to this function, see https://github.com/emacs-mirror/emacs/commit/bc099295dd24d059d3358acf5653ced9c9292e41. The change looks a little bit wild too me. This function has not changed for a long time, and now it was basically replaced in its entirety.
> 
> If you use Emacs 30, we have to check if the upstream change caused the problem and we have to check if the changed behavior is indeed correct. If not, an upstream bug should be submitted. I suspect that other packages would also be affected by this change.
> 
> EDIT: I've reread your issue again and also tested the newest `thing-at-point-looking-at` from Emacs master. I think I've missed the crucial point that you trigger `cape-emoji` directly before a double quote. Unfortunately there is no way right now to exclude such special characters from the pattern, since they can be part of the name of a character. For example `cape-tex` has characters like `\"` where double quotes are included. Emoji names also include special characters like parentheses, so we cannot exclude them in general.

True but I was hoping for `cape-emoji` specifically to not include quotes, though the backends all share the same code.

**Comment by minad** [comment]
> True but I was hoping for cape-emoji specifically to not include double quotes, though the backends all share the same code.

We could try to determine the set of characters during the hash table generation and adjust the regexp accordingly. But I worry that this makes things unnecessarily complicated.

**Comment by minad** [comment]
I've found a better fix. The Capf simply doesn't look further than (point). The small downside is that you cannot complete inside symbols then.
