### ISSUE TITLE
Corfu completion with yasnippet and/or auctex

### ISSUE THREAD

**Issue by thorstengrothe** [minad/corfu#64]
Hi all,

I like the package very much, more than company. Really good work!

I wonder if it works with yasnippet and/or auctex because I'm working a lot with latex. In company there is company-yasnippet.

Could not find anything about it.

Regards
Thorsten

**Comment by minad** [comment]
Thanks!

As far as I know there does not exist a Yasnippet capf backend. Corfu only provides a UI and supports only capf backends. Maybe company-yasnippet can be ported over to implement a capf instead of a company backend? Another more general solution would be a general capf wrapper around company backends. But I am afraid that this will be difficult to get right.

Maybe you also use my Consult and Vertico packages? As alternatives you may want to look into consult-company and consult-yasnippet. These packages integrate Company backends or Yasnippet with Consult and work well with Vertico. It is not related to Corfu though.

cc @mohkale, who is the author of consult-yasnippet and consult-company. He can probably tell you more about available yasnippet UIs. I am neither using yasnippet nor company.

**Comment by mohkale** [comment]
@thorstengrothe 

I don't really have much to contribute here. I've never really used the capf functionality, instead just leaving it up to the major modes to set it for me and then interacting with them through company. Looking at yasnippet atm there doesn't seem to be a capf for it and you should probably open an issue for it on that repository. Since this is the standard for completion and joatavora (the maintainer) is very fond of built-in emacs functionality, over relying on external packages re-implementing part of them, I'm sure he'd be more than happy to accept a PR on this. On the other hand he has mentioned in the past about wanting to write a new/alternative company so maybe you'd want to contribute to that or wait for it.

`consult-yasnippet` doesn't depend on company or capf so you should be able to use it even without those. It lets you interactively select a snippet to expand, Which while not like the completion you get from company or corfu is a pretty convenient way to expand a snippet whose name you don't fully remember. I recommend trying it out.

`consult-company` is a `completion-at-point` alternative for company and presents you with all the company completions at point in a completing-read session. You can, technically, use this without the company-tooltip so you can continue using corfu but also setup company-backends with company-yasnippet and use `consult-company` to complete and insert snippets. But I'd say that'll just give you a lesser experience to `consult-yasnippet` so you may as well use that.

**Comment by thorstengrothe** [comment]
Wow thank you very much both of you for your fast and detailed answers!

Did not know `consult-yasnippet` and `consult-yasnippet` but I have consult installed and I love it. I will try both packages and see if I can work with them!

Thanks again!

**Comment by DivineDominion** [comment]
Anyone who visits this page from search results in 2024, you want yasnippet-capf :) https://github.com/elken/yasnippet-capf/
