### ISSUE TITLE
Complete on minibuffer

### ISSUE THREAD

**Issue by memeplex** [minad/corfu#81]
When entering an expression in the minibuffer (`M-:`) TAB opens the builtin completion buffer instead of corfu popup.  Notice that TAB is bound to `completion-at-point` there.

**Comment by minad** [comment]
Corfu works well in the minibuffer. You can enable `corfu-mode` it manually there.

~~~ elisp
(add-hook 'minibuffer-setup-hook #'corfu-mode)
~~~

`corfu-global-mode` currently does not activate `corfu-mode` in the minibuffer since it could be unexpected and confusing. In particular try to use the default completion UI (not vertico, ivy, icomplete) and enable `corfu-mode` in the minibuffer. Then you will see what I mean. But I may reconsider this in the future.

See also:

https://github.com/minad/corfu/blob/3b01af4baa76bed05ec37f141ca8bc69f713c0c5/corfu.el#L1066-L1071

**Comment by memeplex** [comment]
Ok, thanks! I had already set said hook, actually my report was about `corfu-global-mode` behavior and I now see I should have made that clearer, but I understand your reasons for not enabling it by default. Do you think it's worth adding your explanation above to the README so that the user is both aware of the need to explicitly enable corfu in the minibuffer and the perils of doing so?

**Comment by minad** [comment]
Of course, making the documentation better is always a good idea. As usual, PRs improving the documentation are welcome.

**Comment by memeplex** [comment]
Ok, I will give it a shot in a few days.
