### ISSUE TITLE
Odd empty space at the end of the child frame

### ISSUE THREAD

**Issue by d4ncer** [minad/corfu#82]
<img width="478" alt="Screen Shot 2021-11-17 at 19 52 27" src="https://user-images.githubusercontent.com/1840377/142149167-241b5270-b7b9-4f78-9855-2d35f9330655.png">

I've got a weird empty space at the end of the child frame, and I can't figure out where it's coming from. 

I'm using `JetBrains Mono` on macOS (M1) via `emacs-plus@29`:
```
           Family: JetBrains Mono
          Foundry: nil
            Width: normal
           Height: 180
           Weight: regular
            Slant: normal
       Foreground: #37474F
DistantForeground: unspecified
       Background: #FFFFFF
        Underline: nil
         Overline: nil
   Strike-through: nil
              Box: nil
          Inverse: nil
          Stipple: nil
             Font: #<font-object -*-JetBrains Mono-regular-normal-normal-*-18-*-*-*-m-0-iso10646-1>
          Fontset: -*-JetBrains Mono-regular-normal-normal-*-18-*-*-*-m-0-fontset-auto4
           Extend: nil
          Inherit: nil
```

```
brew install emacs-plus@29 --with-xwidgets --with-mailutils
```

**Comment by d4ncer** [comment]
I've tried a few other fonts to no avail (`Input Mono` & `Fira Code`)

**Comment by minad** [comment]
Oh I have not seen this before.

Did you use emacs -Q to narrow down the cause of this? Do you see the issue in emacs -Q too? If yes it is an emacs upstream bug and should be reported there.

It seems you use nano emacs which heavily modifies many settings. So in order to figure out the problem start with emacs -Q and gradually add nano settings until the problem appears. Then we can find a workaround which overwrites the setting for Corfu.

**Comment by d4ncer** [comment]
Thanks for the quick response! I'll try throwing out all my customisation and working backwards. I'll post my findings here for anyone else who might have a similar issue.

**Comment by d4ncer** [comment]
Ok, it's definitely in my theming somewhere, closing this out.

**Comment by minad** [comment]
You are welcome!

> I'll try throwing out all my customisation and working backwards. I'll post my findings here for anyone else who might have a similar issue.

Thank you, please do! You may also ask on the upstream Nano Emacs repository for help. As far as I know, Nano uses Ivy and Counsel. But maybe there is some interest in supporting Consult/Corfu/Embark/Marginalia/Orderless/Vertico too? Our packages could be a good fit there due to their composeable and minimal nature and tight integration with existing Emacs machinery.

**Comment by d4ncer** [comment]
Narrowed the issue down to [nano-modeline](https://github.com/rougier/nano-emacs/blob/master/nano-modeline.el). It looks like that white space is an errant modeline, now to figure out why.

**Comment by d4ncer** [comment]
Ok, this is the issue: 
```elisp
(defun nano-modeline-update-windows ()
  "Modify the mode line depending on the presence of a window
below or a buffer local variable 'no-mode-line'."
  (dolist (window (window-list))
    (with-selected-window window
	  (with-current-buffer (window-buffer window)
        (if (or (not (boundp 'no-mode-line)) (not no-mode-line))
            (setq mode-line-format 
                  (cond ((one-window-p t) (list ""))
                        ((eq (window-in-direction 'below) (minibuffer-window)) (list ""))
                        ((not (window-in-direction 'below)) (list ""))
                        (t nil))))))))

(add-hook 'window-configuration-change-hook 'nano-modeline-update-windows)
```

It looks like this hook overrides buffer-local vars set in `corfu--make-buffer` as (I suspect) it runs post buffer/window creation and overrides the `mode-line-format`. I now need to figure out what fn to advise and set the `no-mode-line` var to fix this.

**Comment by d4ncer** [comment]
https://github.com/rougier/nano-emacs/pull/104 fixes the issue.
