### ISSUE TITLE
Continuing oop dot completions

### ISSUE THREAD

**Issue by fbergroth** [minad/corfu#95]
Hi, I have the following problem when editing python code via eglot. Let's say we have two variables:
```
aaa = 123
aaaa = 345
```
If I type `aaa` I get completions for both of them. Now I type a `.`, expecting to see completions for the object `aaa`. Instead it filters the completions down to `aaaa`. This doesn't happend with company-mode.

Perhaps completions should be updated when `:company-prefix-length` is `t`? Or could it be related to my setup?

**Comment by minad** [comment]
Try corfu-quit-at-boundary=t. Does this solve your problem? Unfortunately you loose orderless support by doing that. @jdtsmith have you observed this issue too in eglot/lsp-mode?

**Comment by fbergroth** [comment]
> Try `corfu-quit-at-boundary=t`. Does this solve the problem?

Yeah, that does solve my problem. Thank you!

> Probably there is a best of both worlds solution where `.` terminates the completion?

Yes, and I think that generalizes to `:company-prefix-length` being `t`. Other languages has `::`, `->`, etc.

@jdtsmith, perhaps you'd be interested to try https://github.com/joaotavora/eglot/issues/769.

**Comment by jdtsmith** [comment]
I do not see this problem, and I don't have `quit-at-boundary=t`.    But I DO however have a custom [auto-commit](https://github.com/minad/corfu/wiki#auto-commit), which includes:

```elisp
     ((seq-contains-p (this-command-keys-vector) ?.) ; '.', but not after SPC
      (or (string-empty-p (car corfu--input))
	  (not (string= (substring (car corfu--input) -1) " "))))
```

I.e. quits on "." (and then immediately restarts!).  I'm using pyright and lsp-mode.  

@fbergroth interesting example.  lsp-mode is already handling auto-imports automatically. Also, what are the `kind`'s being returned for e.g. `inf` in your example?  That symbol means "don't know".

**Comment by fbergroth** [comment]
> lsp-mode is already handling auto-imports automatically.

@jdtsmith  I guess that is pyright doing it's thing. But can you see the import statement being displayed in the echo area (in the gif) with lsp-mode? Perhaps it's shown via the annotation-function instead of docsig?

> Also, what are the `kind`'s being returned for e.g. `inf` in your example? That symbol means "don't know".

Ah, it's `Constant`, but `eglot--kind-names` was outdated and lacked some entries. I updated it and now it looks better.

**Comment by jdtsmith** [comment]
Aha I'd missed that.  It uses annotation to mention the auto-import:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/93749/146209496-90115df8-53c4-4a59-8861-07acb21664cf.png">

lsp-mode actually gives you nothing in the echo area for docsig (see emacs-lsp/lsp-mode#3201), since it doesn't yet know the calling syntax until the candidate is placed in the buffer.  The recommended solution is to use quick-help from company to pop up a complete help buffer.  Interesting that eglot uses something else entirely for its docsig content.

**Comment by minad** [comment]
@jdtsmith 

> I do not see this problem, and I don't have quit-at-boundary=t. But I DO however have a custom auto-commit, which includes:

Thanks! This is what I meant with the solution which solves both problems. Either one enables the boundary check or one modifies the auto-commit to check for `.`.

**Comment by fbergroth** [comment]
Perhaps I wasn't very clear regarding `:company-prefix-length=t`.

LSP servers can define a list of triggerCharacters, see [CompletionOptions](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionOptions). `pyright` sets it to `[".", "["]`, for `pylsp` it is `["."]`, `clangd` gives it `[".", "<", ">", ":", "\"", "/", "*"]`, and so on. Both eglot and lsp-mode sends `:company-prefix-length=t` when a trigger character was entered.

I think any other capf that sends `:company-prefix-length=t` does it for the same reason.

So rather than hardcoding `.` for python-mode, I was suggesting to check `:company-prefix-length=t` in the general case. What do you think @minad?

**Comment by minad** [comment]
@fbergroth 

> So rather than hardcoding . for python-mode, I was suggesting to check :company-prefix-length=t in the general case. What do you think @minad?

Corfu already respects and checks `:company-prefix-length`. This is not the point. The point is that Corfu does not ask the backend again when entering a `.` or a `SPC`. This behavior is controlled by `corfu-quit-at-boundary` as I already wrote and the intention of `corfu-quit-at-boundary=nil` is to enable Orderless matching/filtering.

**Comment by fbergroth** [comment]
I guess I misunderstood then. `corfu-quit-at-boundary` says "Automatically quit at completion field/word boundary.", and I thought trigger characters could quit as well. Anyway, I'm happy with `corfu-quit-at-boundary=t`.

**Comment by jdtsmith** [comment]
> Corfu already respects and checks :company-prefix-length

Only on initial popup though, right?  I think @fbergroth is asking for corfu to respect the `t` value of :company-prefix-length when deciding whether to refresh as well.  

>  I'm happy with corfu-quit-at-boundary=t.

This boundary is defined by completion-at-point-predicate; does the lsp server get a say in that?

**Comment by minad** [comment]
> Only on initial popup though, right? I think @fbergroth is asking for corfu to respect the t value of :company-prefix-length when deciding whether to refresh as well.

Yes, of course. But Corfu is not working like this. It will ask for the updated table however if corfu-quit-at-boundary=t.

> This boundary is defined by completion-at-point-predicate; does the lsp server get a say in that?

Yes, the capf determines when the completion boundary is crossed. The completion predicate calls the capf again and checks if the start position changed.

**Comment by fbergroth** [comment]
> I think @fbergroth is asking for corfu to respect the `t` value of :company-prefix-length when deciding whether to refresh as well.

It was just a suggestion, that maybe didn't make much sense. I noticed only `.` was mentioned as a problem, but I can see `?` being annoying in rust or typescript, `+` for post-incrementing a variable in C++, perhaps `*` in some situations as well. But with `corfu-quit-at-boundary=t` it's all good.

**Comment by jdtsmith** [comment]
Summarizing the situation — to use orderless, you have to use `corfu-quit-at-boundary`=nil so that space doesn't cause a quit (most backends regard space as a field separator).  Since `:company-prefix-length` is a static value, it can only act _before_ the completion popup, not during; you'll get an initial pop-up on `[".", "<", ">", ":", "\"", "/", "*"]` with clangd, for example. 

To use orderless and have completion triggers dump and renew the list of candidates _during_ completion, it therefore needs to be coded into `corfu-commit-predicate`, as in the wiki example.  I wonder if there is some general way to get your hands on the `triggerCharacters` lsp setting?  Thoughts?

**Comment by minad** [comment]
> I wonder if there is some general way to get your hands on the triggerCharacters lsp setting? Thoughts?

We could propose a corfu-trigger-char/company-trigger-char extension :shrug:

But I am not a fan of adding more and more extensions. One possibility is this:

1. Check in the commit predicate that current input is valid
2. Run the capf. If the return value has prefix=t and a length of 1 we hit a trigger char. Restart completion at that point. Unfortunately we violate the completion-in-region API by doing that since we don't have access to the capf. This means as soon as we do this we invent our own restartable completion in region API. Maybe it is also possible to implement this on the level of Cape, but I doubt it.

**Comment by minad** [comment]
Ah I know how could implement this on the level of cape. One would have to implement a completion table which returns completion boundaries. The boundaries would have to be computed by doing the capf query trick I described above. I suspect it won't be easy to do this correctly, but I am pretty sure it is possible. 

Completions like object.field.subfield are exactly what completion boundaries are made for. So in order to implement this in the style of the emacs API one would have to make use of boundaries. Unfortunately there is a significant impedance mismatch with the lsp backends.

**Comment by jdtsmith** [comment]
Good stuff.  I was proposing the simpler approach of asking lsp-mode for the server's fixed list of `triggerCharacters`, so I could bake them into the `corfu-commit-predicate` (instead of just `.`).  For example, by examining the `pyright` traffic I can see:

```json
    "completionProvider": {
      "workDoneProgress": true,
      "resolveProvider": true,
      "triggerCharacters": [
        ".",
        "["
      ]
    },
```

Just not sure how to get my hands on that (I've asked in the lsp-mode discussions). 

Interesting ideas about boundaries.  I've actually misused (?) boundaries to help solve the impedance mismatch of not knowing the completion region in advance when my ipython capf is first called.  I guess a relatively "generous" region, then when the process responds, use boundaries to mark what was actually completed.  Seems to work OK.

**Comment by minad** [comment]
@jdtsmith Yes, I understood your goal and approach. I was just trying to point out that completion boundaries are the correct solution to the problem if one sticks to the Emacs API. Abusing the completion predicate to achieve something similar is nothing else than patching up the deficiencies of the backends. If one looks at cape-file one can see the capabilities of completion boundaries. I'd imagine that completing object hierarchies should ideally behave in the same way. As an approach one could also try to write our own more capable lsp-capf, since nothing should prevent us from accessing the lsp apis directly. If this turns out to be successful one could propose such a more capable capf to the lsp-mode team.

**Comment by jdtsmith** [comment]
Indeed a bit of a workaround, but perhaps useful for @fbergroth in the meantime.  

I do see the appeal of making `x.a.foo['test'].bar` into a "continuing boundaries" problem ala cape-file.  Might be tricky in practice though.  The lsp-server doesn't give "full paths", but only "the next piece".  E.g. for `np.`, you get various entries like:

```json
    {
      "sortText": "09.9999.Arrayterator",
      "data": {
        "symbolLabel": "Arrayterator",
        "position": {
          "character": 3,
          "line": 25
        },
        "filePath": "XXX/python/scraps/test.py",
        "workspacePath": "XXX/python/scraps"
      },
      "kind": 7,
      "label": "Arrayterator"
    },
```

without indication that they have more beneath them (as this one does), other than (perhaps) the `kind` (likely language-dependent) 

BTW, `corfu-commit-predicate` is perhaps no longer well-named, since you can "commit" your entered text, which is tantamount to dumping the table and trying again.  `corfu-commit-or-refresh-predicate`?
