### ISSUE TITLE
Even more advanced LSP-mode + orderless setup

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#96]
I am now using an additional orderless dispatcher (first on the list) instead of first-pattern = flex (updated):

```elisp
  (defun my/orderless-dispatch-passthrough-first ()
    (let (last-table initial-pattern)
      (lambda (pattern index _total)
	(if-let (((eq index 0))
		 (table (caddr completion-in-region--data)))
	    (cond
	     ;; new table of results: save pattern and let all matches through
	     ((not (eq table last-table))
	      (setq last-table table
		    initial-pattern pattern)
	      "")
	     
	     ;; Unchanged initial pattern: let all matches through
	     ((and initial-pattern 
		   (string-equal pattern initial-pattern))
	      "")

	     ;; Pattern has changed: fall back on flex matching
	     (t 'orderless-flex))))))

   (cl-pushnew (my/orderless-dispatch-passthrough-first)
		orderless-style-dispatchers)
```

Instead of flex, this simply passes through _everything_ the first orderless pattern matches, as long as that first term is unaltered since the table was created.  Worth adding to the wiki as "even more advanced" lsp-mode setup?  Maybe overkill, but flex in fact does miss a few things (and its highlighting essentially lies about why the lsp server selected a candidate).  It's also quite a bit faster to match against an empty regexp than flex.

**Comment by minad** [comment]
Feel free to add it to the wiki, but maybe as a separate section with a big disclaimer. I don't think anyone should use this except for people who actually know what is going on here. And I suspect that not many people are that familiar with orderless style dispatchers. Users should familiarize themselves first with how these style dispatchers work in detail. Furthermore you may want to rewrite your snippet with `cond` and add comments for each of the steps.

But when I think a bit about this, the approach you are using is not such a good idea and I would probably not recommend it. If you type "init" you say that "init" should be ignored since we want the results from the server to get through unaltered. So far so good. But as soon as you continue to extend the prefix "initial" you switch to the usual orderless filtering. I don't understand why this is acceptable then, since at this point we start to lose candidates (more than we may want to lose). You suddenly switch the semantics of the first word from unfiltered to orderless-filtered.

**Comment by jdtsmith** [comment]
> But when I think a bit about this, the approach you are using is not such a good idea and I would probably not recommend it. If you type "init" you say that "init" should be ignored since we want the results from the server to get through unaltered. So far so good. But as soon as you continue to extend the prefix "initial" you switch to the usual orderless filtering. 

This is what happens _by default_.  Once a completion table is live, further extensions to the prefix (init->initial) do _not_ result in it being dumped.  This is true even if the backend is behaving correctly, or we use cape-capf-buster to make it behave.  The orderless dispatcher passthrough simply creates an exception to this non-ideal default — when the initial list of candidates is obtained from the lsp server, show them in their entirety. 

I agree the further filtering could be disconcerting.  You could of course fall back on flex matching on the 1st pattern (once altered) to make it a smaller and less disruptive cull, while still getting the performance benefits on initial lsp response.  That seems to be a sensible middle ground; I've updated my dispatcher above. 

And of course we could arrange for corfu + orderless to be even more aggressive with table dumping, effectively treating the 1st orderless pattern as company does (any deletion/addition causing a table dump).  But I suspect that's a bit too much.  Otherwise, you are left to sensibly reason, as I have, that extending the 1st pattern inherently constitutes "additional filtering". 

> I don't understand why this is acceptable then, since at this point we start to lose candidates (more than we may want to lose). You suddenly switch the semantics of the first word from unfiltered to orderless-filtered.

Once you admit that the 1st orderless pattern serves two quite distinct functions: priming the lsp-server for a generated candidate list _AND_ filtering those results, you have no choice.  You are forced to decide how to configure those two roles.    No matter what, without aggressive, company-style dumping (as a config for role No. 1):

```elisp
   init|ial   ; lsp is queried on the |
```

vs. 

```elisp
   initial|
```

will result in a different list of candidates.  I personally have gotten quite used to this, and the narrowing performance is worth it (to me).   I guess this is the exact road down which company went before deciding on the aggressive dumping strategy.   

Closing for now and we can think on this a bit to see if it's worth including in the wiki (or implementing elsewhere).

**Comment by minad** [comment]
> This is what happens by default.

No, I am specifically criticizing that you switching the behavior as soon as the initial prefix is extended. By default the initial prefix is always used for filtering. And you change this, and I understand your motivation but I am still critical about the idea. But by all means - please document this in the wiki. It is good to collect these ideas! As longs as it is clearly explained there is no risk for confusion and people who like to dig deeper can look into it.

> I agree the further filtering could be disconcerting. You could of course fall back on flex matching on the 1st pattern (once altered) to make it a smaller and less disruptive cull, while still getting the performance benefits on initial lsp response. That seems to be a sensible middle ground; I've updated my dispatcher above.

Makes sense.

> And of course we could arrange for corfu + orderless to be even more aggressive with table dumping, effectively treating the 1st orderless pattern as company does (any deletion/addition causing a table dump). But I suspect that's a bit too much. 

We have the `cape-capf-buster` which does exactly that or did I miss something. I won't bake this behavior directly into Corfu.

> Otherwise, you are left to sensibly reason, as I have, that extending the 1st pattern inherently constitutes "additional filtering".

I try it again to be more clear what I find unreasonable about your approach: When typing "init", the string "init" is not used for filtering but as soon as you extend it the entire string "init"+"al" is used for filtering. This is a switch in behavior. It would make more sense if you only return the "al" (the substring!) from the style dispatcher.

> Once you admit that the 1st orderless pattern serves two quite distinct functions: priming the lsp-server for a generated candidate list AND filtering those results, you have no choice. You are forced to decide how to configure those two roles. No matter what, without aggressive, company-style dumping (as a config for role No. 1):

I am not sure I understand what you want to tell me here. But I agree with what you say - the initial prefix has a dual role. It is used by the lsp server to generate candidates and it is used for additional client side filtering in Corfu. Your snippet disables this client side filtering, which is perfectly fine. As described above my only problem is what happens when you extend the string. You should only filter on the substring and not the entire string. Does that make sense?
